import "dotenv/config";
import { config } from "dotenv";
import {
  app,
  BrowserWindow,
  ipcMain,
  shell,
  systemPreferences,
  screen,
} from "electron";
import path from "path";
import { DatabaseSync } from "node:sqlite";
import os from "os";
import { spawn, exec } from "child_process";
import { promisify } from "util";
import { randomUUID } from "crypto";
import { runAgentStream } from "../agent/run";
import type { AgentContext } from "../agent";
import { generateObject } from "ai";
import { openai } from "@ai-sdk/openai";
import { z } from "zod";

// Load .env file - dotenv/config loads from process.cwd() by default
// Also try loading from apps/overlay/.env explicitly (doesn't error if file doesn't exist)
const overlayEnvPath = path.join(__dirname, "../../.env");
config({ path: overlayEnvPath });

const execAsync = promisify(exec);

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Vite
// plugin that tells the Electron app where to look for the Vite-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_VITE_DEV_SERVER_URL: string;
declare const MAIN_WINDOW_VITE_NAME: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require("electron-squirrel-startup")) {
  app.quit();
}

const CHAT_DB_PATH = path.join(os.homedir(), "Library/Messages/chat.db");

// Contact cache to avoid re-lookups
const contactCache = new Map<string, string>(); // phone number -> contact name
let contactMap: Map<string, string> | null = null;
let contactMapLoading = false;

// Store the original bottom position to keep it fixed during resizes
let originalBottomY: number | null = null;

const createWindow = (): void => {
  // Get screen dimensions
  const { width: screenWidth, height: screenHeight } =
    screen.getPrimaryDisplay().workAreaSize;

  const windowWidth = 500;
  const windowHeight = 50;
  const bottomMargin = 2; // Distance from bottom of screen

  // Calculate position: centered horizontally, at bottom vertically
  const x = Math.floor((screenWidth - windowWidth) / 2);
  const y = screenHeight - windowHeight - bottomMargin;

  // Create the browser window.
  const mainWindow = new BrowserWindow({
    width: windowWidth,
    height: windowHeight,
    x: x,
    y: y,
    frame: false,
    transparent: true, // Remove backdrop shadow
    hasShadow: true, // Enable window shadow on macOS
    backgroundColor: "#00000000", // Fully transparent background
    webPreferences: {
      preload: path.join(__dirname, "preload.js"),
      nodeIntegration: false,
      contextIsolation: true,
    },
  });

  // and load the index.html of the app.
  if (MAIN_WINDOW_VITE_DEV_SERVER_URL) {
    mainWindow.loadURL(MAIN_WINDOW_VITE_DEV_SERVER_URL);
  } else {
    mainWindow.loadFile(
      path.join(__dirname, `../renderer/${MAIN_WINDOW_VITE_NAME}/index.html`)
    );
  }

  // Store the original bottom position once window is ready
  mainWindow.once("ready-to-show", () => {
    const cb = mainWindow.getContentBounds();
    originalBottomY = cb.y + cb.height;
  });

  // Open the DevTools.
  // Commented out to prevent auto-opening DevTools in development
  // if (!app.isPackaged) {
  //   mainWindow.webContents.openDevTools();
  // }
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on("ready", createWindow);

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on("window-all-closed", () => {
  if (process.platform !== "darwin") {
    app.quit();
  }
});

app.on("activate", () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.

/**
 * Close window handler
 */
ipcMain.on("close-window", () => {
  const window = BrowserWindow.getFocusedWindow();
  if (window) {
    window.close();
  }
});

/**
 * Resize window handler — expand upward while keeping bottom fixed
 */
ipcMain.on("resize-window", (event, newHeight: number, newWidth?: number) => {
  const win = BrowserWindow.fromWebContents(event.sender);
  if (!win) return;

  // Work in content-space so transparent/frame/shadow don't skew math
  const cb = win.getContentBounds();

  // Device-pixel alignment to avoid 1px jitter on scaled displays
  const scale =
    screen.getDisplayMatching(cb).scaleFactor ||
    screen.getPrimaryDisplay().scaleFactor ||
    1;
  const align = (v: number) => Math.round(v * scale) / scale;

  // Use the stored original bottom position, or calculate it if not set
  if (originalBottomY === null) {
    originalBottomY = cb.y + cb.height;
  }

  // Always anchor to the original bottom position
  const targetY = align(originalBottomY - newHeight);

  // Use provided width or keep current width
  const targetWidth = newWidth ? align(newWidth) : align(cb.width);

  // Center horizontally if width changes
  const { width: screenWidth } = screen.getPrimaryDisplay().workAreaSize;
  const targetX = newWidth
    ? align((screenWidth - targetWidth) / 2)
    : align(cb.x);

  win.setContentBounds(
    {
      x: targetX,
      y: targetY,
      width: targetWidth,
      height: align(newHeight),
    },
    /* animate */ true
  );
});

/**
 * Check if we have Full Disk Access to read the iMessage database
 */
ipcMain.handle("check-database-access", async () => {
  try {
    const fs = require("fs");

    // Check if file exists and is readable
    if (!fs.existsSync(CHAT_DB_PATH)) {
      return {
        hasAccess: false,
        path: CHAT_DB_PATH,
        error: "Database file not found",
      };
    }

    // Try to get file stats to verify read access
    const stats = fs.statSync(CHAT_DB_PATH);

    return {
      hasAccess: true,
      path: CHAT_DB_PATH,
      fileSize: stats.size,
      lastModified: stats.mtime,
    };
  } catch (error: any) {
    return {
      hasAccess: false,
      path: CHAT_DB_PATH,
      error: error.message,
    };
  }
});

/**
 * Get database statistics (file size, last modified, etc.)
 */
ipcMain.handle("get-database-stats", async () => {
  try {
    const fs = require("fs");
    const stats = fs.statSync(CHAT_DB_PATH);

    return {
      success: true,
      fileSize: stats.size,
      fileSizeMB: (stats.size / (1024 * 1024)).toFixed(2),
      lastModified: stats.mtime.toISOString(),
      path: CHAT_DB_PATH,
    };
  } catch (error: any) {
    return {
      success: false,
      error: error.message,
    };
  }
});

/**
 * Get list of tables in the database
 */
ipcMain.handle("get-database-tables", async () => {
  let db: DatabaseSync | null = null;
  try {
    db = new DatabaseSync(CHAT_DB_PATH, { readOnly: true });

    const tablesQuery = db.prepare(`
      SELECT name, type 
      FROM sqlite_master 
      WHERE type IN ('table', 'view')
      ORDER BY name
    `);

    const tables = tablesQuery.all() as Array<{ name: string; type: string }>;

    return {
      success: true,
      tables,
      totalCount: tables.length,
    };
  } catch (error: any) {
    return {
      success: false,
      error: error.message,
      tables: [],
      totalCount: 0,
    };
  } finally {
    if (db) {
      db.close();
    }
  }
});

/**
 * Open System Preferences to Full Disk Access pane
 */
ipcMain.handle("open-system-preferences", async () => {
  try {
    // Open the Full Disk Access settings pane
    shell.openExternal(
      "x-apple.systempreferences:com.apple.preference.security?Privacy_AllFiles"
    );
    return { success: true };
  } catch (error: any) {
    return {
      success: false,
      error: error.message,
    };
  }
});

/**
 * Helper function to safely convert Apple timestamp (which can be very large) to number
 * Apple timestamps are in nanoseconds since 2001-01-01
 */
function safeTimestampToNumber(timestamp: any): number | null {
  if (timestamp === null || timestamp === undefined) {
    return null;
  }

  // If it's already a number and within safe range, return it
  if (typeof timestamp === "number") {
    return timestamp;
  }

  // If it's a string (from CAST AS TEXT), parse it
  if (typeof timestamp === "string") {
    try {
      // Use BigInt to handle large numbers, then convert to regular number
      const bigIntValue = BigInt(timestamp);
      // Convert to number (may lose precision but that's okay for timestamps)
      return Number(bigIntValue);
    } catch {
      return null;
    }
  }

  // Try parsing as BigInt if it's some other type
  try {
    const bigIntValue = BigInt(timestamp);
    return Number(bigIntValue);
  } catch {
    // Fallback to direct conversion
    return Number(timestamp);
  }
}

/**
 * Check if a text chunk looks like binary metadata/artifacts
 */
function isBinaryArtifact(chunk: string): boolean {
  const lower = chunk.toLowerCase();

  // Filter out NSObject-related patterns
  if (
    lower.includes("nsattributedstring") ||
    lower.includes("nsobject") ||
    lower.includes("nsdictionary") ||
    lower.includes("nsmutable") ||
    lower.includes("nsstring") ||
    lower.includes("nsnumber") ||
    lower.includes("nsvalue") ||
    lower.includes("streamtyped") ||
    lower.includes("__kim")
  ) {
    return true;
  }

  // Filter out binary plist markers (X$version, Y$archiver, T$top, etc.)
  if (/\$version|\$archiver|\$top|\$objects|X\$|Y\$|T\$|Z\$/.test(chunk)) {
    return true;
  }

  // Filter out NS.rangeval, NS.special, NS.location patterns
  if (/NS\.(rangeval|special|location|objects|classname)/i.test(chunk)) {
    return true;
  }

  // Filter out patterns that look like binary metadata (containing $ and version/archiver)
  if (
    chunk.includes("$") &&
    (lower.includes("version") ||
      lower.includes("archiver") ||
      lower.includes("objects"))
  ) {
    return true;
  }

  // Filter out pure numbers
  if (/^\d+$/.test(chunk)) {
    return true;
  }

  return false;
}

/**
 * Remove binary artifact patterns from text, even when embedded in longer strings
 */
function removeBinaryArtifacts(text: string): string {
  let cleaned = text;

  // Remove concatenated patterns like "X$versionY$archiverT$topX$objects" (no spaces between)
  // This catches patterns where multiple $ markers are concatenated together
  cleaned = cleaned.replace(
    /[XYZ]\$[a-zA-Z]+[XYZ]\$[a-zA-Z]+[TZ]\$[a-zA-Z]+[XYZ]\$[a-zA-Z]+/g,
    ""
  );

  // Remove individual binary plist patterns (X$version, Y$archiver, T$top, Z$objects, etc.)
  cleaned = cleaned.replace(/[XYZ]\$[a-zA-Z]+/g, "");
  cleaned = cleaned.replace(/T\$[a-zA-Z]+/g, "");
  cleaned = cleaned.replace(/\$[a-zA-Z]+/g, "");

  // Remove NS. patterns (NS.rangeval, NS.special, NS.location, etc.)
  // Also handle cases like "NS.rangeval.locationZNS.special" where Z might be between
  cleaned = cleaned.replace(/NS\.[a-zA-Z]+/g, "");
  cleaned = cleaned.replace(/[A-Z]NS\.[a-zA-Z]+/g, ""); // Handle ZNS.special, etc.

  // Remove patterns with $ followed by version/archiver/objects/top (with or without surrounding chars)
  cleaned = cleaned.replace(/\S*\$version\S*/gi, "");
  cleaned = cleaned.replace(/\S*\$archiver\S*/gi, "");
  cleaned = cleaned.replace(/\S*\$objects\S*/gi, "");
  cleaned = cleaned.replace(/\S*\$top\S*/gi, "");

  // Remove NSObject class names (with word boundaries)
  cleaned = cleaned.replace(
    /\bNS(AttributedString|Object|Dictionary|Mutable|String|Number|Value|Array|Data)\b/gi,
    ""
  );

  // Remove streamtyped
  cleaned = cleaned.replace(/\bstreamtyped\b/gi, "");

  // Remove __kIM patterns
  cleaned = cleaned.replace(/\b__kIM\w+\b/gi, "");

  // Remove patterns like "rangeval.location" or standalone metadata words
  cleaned = cleaned.replace(
    /\b(rangeval|special|location|objects|classname|archiver|version)\.[a-zA-Z]+\b/gi,
    ""
  );

  // Remove patterns like "locationZNS" where a metadata word is concatenated with NS
  cleaned = cleaned.replace(
    /\b(rangeval|special|location|objects|classname)[A-Z]+NS\b/gi,
    ""
  );

  // Remove standalone metadata words that might appear (rangeval, special, etc.)
  cleaned = cleaned.replace(
    /\b(rangeval|special|location|objects|classname)\b/gi,
    ""
  );

  // Remove any word that contains both a metadata term and NS (like "locationZNS")
  cleaned = cleaned.replace(
    /\b\w*(rangeval|special|location|objects|classname)\w*NS\w*\b/gi,
    ""
  );
  cleaned = cleaned.replace(
    /\b\w*NS\w*(rangeval|special|location|objects|classname)\w*\b/gi,
    ""
  );

  // Clean up multiple spaces and periods/spaces
  cleaned = cleaned.replace(/\s+/g, " ");
  cleaned = cleaned.replace(/\.\s*\./g, "."); // Remove double periods
  cleaned = cleaned.trim();

  return cleaned;
}

/**
 * Helper function to extract text from a message
 * Handles both plain text field and attributedBody binary data
 * Based on research from imessage-db-exploration.md and SQL exploration
 *
 * The attributedBody format stores text as readable UTF-8 strings embedded in the binary data.
 */
function extractMessageText(
  text: string | null,
  attributedBody: Buffer | null
): string | null {
  // If plain text is available, use it
  if (text) {
    return text;
  }

  // Otherwise, try to extract from attributedBody
  if (!attributedBody) {
    return null;
  }

  try {
    const textChunks: string[] = [];

    // Convert to Buffer if it's not already (node-sqlite returns Uint8Array)
    const buffer = Buffer.isBuffer(attributedBody)
      ? attributedBody
      : Buffer.from(attributedBody);

    // Scan the entire buffer sequentially for readable ASCII text sequences
    // Look for sequences of printable ASCII characters (32-126)
    let textStart = -1;
    let textLength = 0;

    for (let i = 0; i < buffer.length; i++) {
      const byte = buffer[i];
      // Only printable ASCII for now (32-126)
      const isPrintable = byte >= 32 && byte <= 126;

      if (isPrintable) {
        if (textStart === -1) {
          textStart = i;
        }
        textLength++;
      } else {
        // End of printable sequence - extract if long enough (at least 3 chars)
        if (textLength >= 3 && textStart !== -1) {
          try {
            const chunk = buffer.subarray(textStart, textStart + textLength);
            const decoded = chunk.toString("ascii");
            // Must contain letters and be meaningful
            if (decoded.length >= 3 && /[A-Za-z]/.test(decoded)) {
              const trimmed = decoded.trim();
              // Filter out binary artifacts
              if (!isBinaryArtifact(trimmed)) {
                textChunks.push(trimmed);
              }
            }
          } catch (e) {
            // Skip invalid sequences
          }
        }
        textStart = -1;
        textLength = 0;
      }
    }

    // Handle text that extends to end of buffer
    if (textLength >= 3 && textStart !== -1) {
      try {
        const chunk = buffer.subarray(textStart, textStart + textLength);
        const decoded = chunk.toString("ascii");
        if (decoded.length >= 3 && /[A-Za-z]/.test(decoded)) {
          const trimmed = decoded.trim();
          if (!isBinaryArtifact(trimmed)) {
            textChunks.push(trimmed);
          }
        }
      } catch (e) {
        // Skip invalid sequences
      }
    }

    if (textChunks.length === 0) {
      return null;
    }

    // Join chunks, removing duplicates and cleaning up
    // Sort by length (longest first) to prioritize actual message content
    const sortedChunks = [...new Set(textChunks)].sort(
      (a, b) => b.length - a.length
    );

    // Take the longest chunks (likely the actual message)
    const topChunks = sortedChunks
      .slice(0, 3)
      .filter((c) => c.length >= 3 && !isBinaryArtifact(c));
    let result = topChunks.join(" ");

    // If we didn't get good results, try all chunks (but still filter artifacts)
    if (result.length < 5) {
      result = sortedChunks.filter((c) => !isBinaryArtifact(c)).join(" ");
    }

    // Final cleanup - remove any remaining binary artifacts that might have slipped through
    // First, remove artifact patterns from the entire string
    result = removeBinaryArtifacts(result);

    // Then split by spaces and filter out individual words that are artifacts
    const words = result.split(/\s+/).filter((word) => {
      // Keep words that don't look like binary artifacts
      return !isBinaryArtifact(word) && word.length > 0;
    });

    result = words
      .join(" ")
      .replace(/\s+/g, " ") // Multiple spaces to single
      .replace(/\n{3,}/g, "\n\n") // Max 2 consecutive newlines
      .trim();

    // Must have meaningful content
    if (result.length < 2 || !/[A-Za-z]/.test(result)) {
      return null;
    }

    return result;
  } catch (error) {
    console.error("Error extracting text from attributedBody:", error);
    return null;
  }
}

/**
 * Normalize phone number for matching (remove formatting, keep + and digits)
 */
function normalizePhoneNumber(phone: string): string {
  // Remove all non-digit characters except +
  return phone.replace(/[^\d+]/g, "");
}

/**
 * Load all contacts from Contacts app via Swift CLI
 * Uses native Contacts framework - much faster than AppleScript
 */
async function loadContactMap(): Promise<Map<string, string>> {
  // Return existing map if already loaded
  if (contactMap) {
    return contactMap;
  }

  // If already loading, wait a bit and return empty map
  if (contactMapLoading) {
    return new Map();
  }

  contactMapLoading = true;

  try {
    console.log("Loading contacts from Contacts app...");

    // Path to the contacts_dump binary (should be in the same directory)
    const binaryPath = app.isPackaged
      ? path.join(process.resourcesPath, "contacts_dump")
      : path.join(__dirname, "../../contacts_dump");

    console.log(`[Contacts] Using binary at: ${binaryPath}`);

    // Execute the Swift binary
    const proc = spawn(binaryPath, [], {
      stdio: ["pipe", "pipe", "pipe"],
    });

    let stdout = "";
    let stderr = "";

    proc.stdout.on("data", (data) => {
      stdout += data.toString();
    });

    proc.stderr.on("data", (data) => {
      stderr += data.toString();
    });

    await new Promise<void>((resolve, reject) => {
      proc.on("close", (code) => {
        if (code === 0) {
          resolve();
        } else {
          reject(
            new Error(`contacts_dump exited with code ${code}: ${stderr}`)
          );
        }
      });

      proc.on("error", (err) => {
        reject(err);
      });
    });

    // Parse JSON output
    const jsonData = stdout.trim();
    const map = new Map<string, string>();

    type PersonEntry = { name: string; phones: { numberRaw: string }[] };
    const contacts: PersonEntry[] = JSON.parse(jsonData);

    console.log(`Loaded ${contacts.length} contacts from Contacts app`);

    // Build the map with multiple normalized formats for each phone number
    for (const contact of contacts) {
      const name = contact.name.trim();
      if (!name || name === "Unknown") continue;

      for (const phoneEntry of contact.phones) {
        const phoneRaw = phoneEntry.numberRaw;
        if (!phoneRaw) continue;

        const normalized = normalizePhoneNumber(phoneRaw);

        // Store many different format variations to maximize matching
        const variants = new Set<string>();

        // Add the normalized version
        variants.add(normalized);

        // Add without leading +
        if (normalized.startsWith("+")) {
          variants.add(normalized.slice(1));
        }

        // Add without +1 prefix
        if (normalized.startsWith("+1")) {
          variants.add(normalized.slice(2));
        }

        // Add without 1 prefix
        if (normalized.startsWith("1") && normalized.length === 11) {
          variants.add(normalized.slice(1));
        }

        // Add last 10 digits (US phone number)
        if (normalized.length >= 10) {
          variants.add(normalized.slice(-10));
        }

        // Add last 7 digits (local number)
        if (normalized.length >= 7) {
          variants.add(normalized.slice(-7));
        }

        // Add with +1 prefix if not present and looks like US number
        if (!normalized.startsWith("+") && normalized.length === 10) {
          variants.add("+1" + normalized);
          variants.add("1" + normalized);
        }

        // Store all variants
        for (const variant of variants) {
          if (variant.length >= 7) {
            // Only store variants with reasonable length
            map.set(variant, name);
          }
        }
      }
    }

    console.log(`Built contact map with ${map.size} phone number mappings`);

    // Debug: Show a sample of what's in the map
    const sampleEntries = Array.from(map.entries()).slice(0, 10);
    console.log(`[Contact Map] Sample entries:`, sampleEntries);

    contactMap = map;
    return map;
  } catch (error: any) {
    console.error("Error loading contacts:", error);
    console.error("Error details:", {
      message: error.message,
      code: error.code,
      signal: error.signal,
    });
    // Return empty map on error
    contactMap = new Map();
    return contactMap;
  } finally {
    contactMapLoading = false;
  }
}

/**
 * Load contacts for specific phone numbers
 * Loads the full contact map once, then uses it for lookups
 */
async function loadContactsForNumbers(phoneNumbers: string[]): Promise<void> {
  // If map is already loaded, we don't need to do anything
  if (contactMap) {
    return;
  }

  // Load the full contact map
  const map = await loadContactMap();

  // Cache the lookups
  for (const phone of phoneNumbers) {
    const name = lookupContactName(phone);
    if (name) {
      contactCache.set(phone, name);
    }
  }
}

/**
 * Check if a phone number is valid (not a short code or invalid)
 */
function isValidPhoneNumber(phone: string): boolean {
  const normalized = normalizePhoneNumber(phone);
  // Must be at least 10 digits (US phone number) or have + and be reasonable length
  if (normalized.startsWith("+")) {
    // International: +1XXXXXXXXXX (11 chars minimum) or longer
    return normalized.length >= 11;
  }
  // Domestic: at least 10 digits
  return normalized.length >= 10;
}

/**
 * Look up contact name from phone number or email
 * Uses pre-loaded contact map (must be loaded separately)
 */
function lookupContactName(identifier: string): string | null {
  if (!identifier) return null;

  // Check cache first
  if (contactCache.has(identifier)) {
    return contactCache.get(identifier) || null;
  }

  // Email addresses - return as is for now
  if (identifier.includes("@")) {
    return null;
  }

  // Phone number - check contact map
  if (!contactMap) {
    return null;
  }

  // Try various normalized formats (matching what we store in the map)
  const normalized = normalizePhoneNumber(identifier);
  const formats = new Set<string>();

  // Add original and normalized
  formats.add(identifier);
  formats.add(normalized);

  // Add without leading +
  if (normalized.startsWith("+")) {
    formats.add(normalized.slice(1));
  }

  // Add without +1 prefix
  if (normalized.startsWith("+1")) {
    formats.add(normalized.slice(2));
  }

  // Add without 1 prefix
  if (normalized.startsWith("1") && normalized.length === 11) {
    formats.add(normalized.slice(1));
  }

  // Add last 10 digits (US phone number)
  if (normalized.length >= 10) {
    formats.add(normalized.slice(-10));
  }

  // Add last 7 digits (local number)
  if (normalized.length >= 7) {
    formats.add(normalized.slice(-7));
  }

  // Add with +1 prefix if not present and looks like US number
  if (!normalized.startsWith("+") && normalized.length === 10) {
    formats.add("+1" + normalized);
    formats.add("1" + normalized);
  }

  // Try each format
  for (const format of formats) {
    const name = contactMap.get(format);
    if (name) {
      // Cache it
      contactCache.set(identifier, name);
      return name;
    }
  }

  return null;
}

type AgentContextRow = {
  text: string | null;
  attributedBody: Buffer | null;
  is_from_me: number;
  date: string;
  handle_identifier: string | null;
  display_name: string | null;
  chat_identifier: string;
};

async function buildAgentContext(
  chatGuid: string,
  messages?: Array<{
    text: string;
    isFromMe: boolean;
    handleId?: string;
    date: number;
  }>
): Promise<AgentContext> {
  // If messages are provided, use them directly
  if (messages && messages.length > 0) {
    // Get contact name from database
    let contactName: string | undefined;
    let db: DatabaseSync | null = null;
    try {
      db = new DatabaseSync(CHAT_DB_PATH, { readOnly: true });
      const chatStmt = db.prepare(`
        SELECT display_name, chat_identifier
        FROM chat
        WHERE guid = ?
        LIMIT 1
      `);
      const chatRow = chatStmt.get(chatGuid) as
        | {
            display_name: string | null;
            chat_identifier: string | null;
          }
        | undefined;
      contactName =
        chatRow?.display_name || chatRow?.chat_identifier || undefined;
    } finally {
      if (db) {
        db.close();
      }
    }

    return {
      contactName,
      conversation: messages.map((msg) => ({
        isFromMe: msg.isFromMe,
        text: msg.text,
      })),
    };
  }

  // Fallback: query database (for backward compatibility)
  let db: DatabaseSync | null = null;
  let rows: AgentContextRow[] = [];
  try {
    db = new DatabaseSync(CHAT_DB_PATH, { readOnly: true });
    const stmt = db.prepare(`
      SELECT 
        m.text,
        m.attributedBody,
        CAST(m.date AS TEXT) as date,
        m.is_from_me,
        h.id as handle_identifier,
        c.display_name,
        c.chat_identifier
      FROM message m
      INNER JOIN chat_message_join cmj ON m.ROWID = cmj.message_id
      INNER JOIN chat c ON cmj.chat_id = c.ROWID
      LEFT JOIN handle h ON m.handle_id = h.ROWID
      WHERE c.guid = ?
        AND m.item_type = 0
        AND m.is_finished = 1
        AND m.is_system_message = 0
      ORDER BY m.date DESC
      LIMIT 30
    `);
    rows = stmt.all(chatGuid) as AgentContextRow[];
  } finally {
    if (db) {
      db.close();
    }
  }

  if (!rows.length) {
    let fallbackName: string | undefined;
    let fallbackDb: DatabaseSync | null = null;
    try {
      fallbackDb = new DatabaseSync(CHAT_DB_PATH, { readOnly: true });
      const chatStmt = fallbackDb.prepare(`
        SELECT display_name, chat_identifier
        FROM chat
        WHERE guid = ?
        LIMIT 1
      `);
      const chatRow = chatStmt.get(chatGuid) as
        | {
            display_name: string | null;
            chat_identifier: string | null;
          }
        | undefined;
      fallbackName =
        chatRow?.display_name ?? chatRow?.chat_identifier ?? undefined;
    } finally {
      if (fallbackDb) {
        fallbackDb.close();
      }
    }
    return {
      contactName: fallbackName,
      conversation: [],
    };
  }

  const phoneNumbers = rows
    .map((row) => row.handle_identifier)
    .filter(
      (identifier): identifier is string =>
        typeof identifier === "string" &&
        !identifier.includes("@") &&
        isValidPhoneNumber(identifier)
    );

  const numbersToLoad = phoneNumbers.filter((num) => !contactCache.has(num));
  if (numbersToLoad.length > 0) {
    await loadContactsForNumbers(numbersToLoad);
  }

  let contactName: string | undefined;
  const displayNameRow = rows.find((row) => row.display_name);
  if (displayNameRow?.display_name) {
    contactName = displayNameRow.display_name;
  } else {
    const handleRow = rows.find((row) => row.handle_identifier);
    if (handleRow?.handle_identifier) {
      contactName = lookupContactName(handleRow.handle_identifier) ?? undefined;
    }
  }

  if (!contactName) {
    const identifierRow = rows.find((row) => row.chat_identifier);
    if (identifierRow?.chat_identifier) {
      contactName = identifierRow.chat_identifier;
    }
  }

  const conversation = rows
    .map((row) => {
      const messageText = extractMessageText(row.text, row.attributedBody);
      return {
        isFromMe: row.is_from_me === 1,
        text: messageText ?? "",
      };
    })
    .reverse();

  return {
    contactName,
    conversation,
  };
}

/**
 * Get all unread messages
 * Returns flat list of unread messages ordered by date (newest first)
 */
ipcMain.handle("get-unread-messages", async (_, limit?: number) => {
  let db: DatabaseSync | null = null;
  try {
    db = new DatabaseSync(CHAT_DB_PATH, { readOnly: true });

    // Query for unread messages with related info
    // We'll get the chat identifier and display name for each message
    const query = `
      SELECT 
        m.ROWID,
        m.guid,
        m.text,
        m.attributedBody,
        CAST(m.date AS TEXT) as date,
        m.is_from_me,
        m.handle_id,
        m.service,
        m.cache_has_attachments,
        m.item_type,
        m.is_read,
        CAST(m.date_read AS TEXT) as date_read,
        m.associated_message_guid,
        m.associated_message_type,
        m.associated_message_emoji,
        c.ROWID as chat_id,
        c.chat_identifier,
        c.display_name,
        h.id as handle_identifier
      FROM message m
      INNER JOIN chat_message_join cmj ON m.ROWID = cmj.message_id
      INNER JOIN chat c ON cmj.chat_id = c.ROWID
      LEFT JOIN handle h ON m.handle_id = h.ROWID
      WHERE m.is_read = 0 
        AND m.is_from_me = 0
        AND m.item_type = 0
        AND m.is_finished = 1
        AND m.is_system_message = 0
      ORDER BY m.date DESC
      ${limit ? `LIMIT ${limit}` : ""}
    `;

    const stmt = db.prepare(query);
    const rows = stmt.all() as Array<{
      ROWID: number;
      guid: string;
      text: string | null;
      attributedBody: Buffer | null;
      date: string;
      is_from_me: number;
      handle_id: number | null;
      service: string | null;
      cache_has_attachments: number;
      item_type: number;
      is_read: number;
      date_read: string | null;
      associated_message_guid: string | null;
      associated_message_type: number | null;
      associated_message_emoji: string | null;
      chat_id: number;
      chat_identifier: string;
      display_name: string | null;
      handle_identifier: string | null;
    }>;

    // Collect unique phone numbers from all unread messages
    const phoneNumberSet = new Set<string>();
    const phoneNumberList: Array<{ phone: string; date: number }> = [];

    for (const row of rows) {
      if (row.handle_identifier && !row.handle_identifier.includes("@")) {
        if (isValidPhoneNumber(row.handle_identifier)) {
          phoneNumberSet.add(row.handle_identifier);
          phoneNumberList.push({
            phone: row.handle_identifier,
            date: safeTimestampToNumber(row.date) ?? 0,
          });
        }
      }
    }

    // Load contacts only for the specific phone numbers we need
    const numbersToLoad = phoneNumberList
      .filter((item) => !contactCache.has(item.phone))
      .map((item) => item.phone);

    if (numbersToLoad.length > 0) {
      await loadContactsForNumbers(numbersToLoad);
    }

    const messages = rows.map((row) => {
      // Extract text (handles both plain text and attributedBody)
      const messageText = extractMessageText(row.text, row.attributedBody);

      return {
        id: String(row.ROWID),
        guid: row.guid,
        text: messageText,
        attributedBody: null, // Don't send binary data to renderer
        date: safeTimestampToNumber(row.date) ?? 0,
        isFromMe: row.is_from_me === 1,
        handleId: row.handle_id ? String(row.handle_id) : null,
        service: row.service,
        cacheHasAttachments: row.cache_has_attachments === 1,
        itemType: row.item_type,
        isRead: row.is_read === 1,
        dateRead: safeTimestampToNumber(row.date_read),
        associatedMessageGuid: row.associated_message_guid,
        associatedMessageType: row.associated_message_type,
        associatedMessageEmoji: row.associated_message_emoji,
        conversationId: String(row.chat_id),
        // Additional fields for display
        chatIdentifier: row.chat_identifier,
        displayName: row.display_name,
        handleIdentifier: row.handle_identifier,
        // Look up contact name (synchronous now - map is pre-loaded)
        contactName: row.handle_identifier
          ? lookupContactName(row.handle_identifier)
          : null,
      };
    });

    return {
      success: true,
      messages,
      count: messages.length,
    };
  } catch (error: any) {
    console.error("Error getting unread messages:", error);
    return {
      success: false,
      error: error.message,
      messages: [],
      count: 0,
    };
  } finally {
    if (db) {
      db.close();
    }
  }
});

/**
 * Get unread messages grouped by conversation/chat
 * Returns conversations with their unread messages
 */
ipcMain.handle("get-unread-conversations", async () => {
  let db: DatabaseSync | null = null;
  try {
    db = new DatabaseSync(CHAT_DB_PATH, { readOnly: true });

    // First, get all chats with unread counts
    const chatStmt = db.prepare(`
      SELECT 
        c.ROWID,
        c.guid,
        c.chat_identifier,
        c.display_name,
        c.style,
        c.service_name,
        CAST(c.last_read_message_timestamp AS TEXT) as last_read_message_timestamp,
        COUNT(DISTINCT m.ROWID) as unread_count,
        CAST(MAX(m.date) AS TEXT) as last_activity
      FROM chat c
      INNER JOIN chat_message_join cmj ON c.ROWID = cmj.chat_id
      INNER JOIN message m ON cmj.message_id = m.ROWID
      WHERE m.is_read = 0
        AND m.is_from_me = 0
        AND m.item_type = 0
        AND m.is_finished = 1
        AND m.is_system_message = 0
      GROUP BY c.ROWID
      ORDER BY MAX(m.date) DESC
    `);

    const chats = chatStmt.all() as Array<{
      ROWID: number;
      guid: string;
      chat_identifier: string;
      display_name: string | null;
      style: number | null;
      service_name: string | null;
      last_read_message_timestamp: string | null;
      unread_count: number;
      last_activity: string;
    }>;

    // Pre-load contacts for all unread messages
    const phoneNumberSet = new Set<string>();
    const phoneNumberList: Array<{ phone: string; date: number }> = [];

    // Get all unread messages to collect phone numbers
    const allMessagesStmt = db.prepare(`
      SELECT DISTINCT
        h.id as handle_identifier,
        CAST(MAX(m.date) AS TEXT) as latest_date
      FROM message m
      INNER JOIN chat_message_join cmj ON m.ROWID = cmj.message_id
      LEFT JOIN handle h ON m.handle_id = h.ROWID
      WHERE m.is_read = 0
        AND m.is_from_me = 0
        AND m.item_type = 0
        AND m.is_finished = 1
        AND m.is_system_message = 0
        AND h.id IS NOT NULL
      GROUP BY h.id
      ORDER BY MAX(m.date) DESC
    `);

    const phoneRows = allMessagesStmt.all() as Array<{
      handle_identifier: string;
      latest_date: string;
    }>;

    for (const row of phoneRows) {
      if (row.handle_identifier && !row.handle_identifier.includes("@")) {
        // Only include valid phone numbers
        if (isValidPhoneNumber(row.handle_identifier)) {
          phoneNumberSet.add(row.handle_identifier);
          phoneNumberList.push({
            phone: row.handle_identifier,
            date: safeTimestampToNumber(row.latest_date) ?? 0,
          });
        }
      }
    }

    // Step 2: Check which numbers we need to load (not already in cache)
    const numbersToLoad = phoneNumberList
      .filter((item) => !contactCache.has(item.phone))
      .map((item) => item.phone);

    // Step 3: Load contacts only for the specific phone numbers we need
    if (numbersToLoad.length > 0) {
      await loadContactsForNumbers(numbersToLoad);
    }

    // Step 4: For each chat, get the unread messages
    const conversations = chats.map((chat) => {
      // Get unread messages for this chat
      const messagesStmt = db!.prepare(`
        SELECT 
          m.ROWID,
          m.guid,
          m.text,
          m.attributedBody,
          CAST(m.date AS TEXT) as date,
          m.is_from_me,
          m.handle_id,
          m.service,
          m.cache_has_attachments,
          m.item_type,
          m.is_read,
          CAST(m.date_read AS TEXT) as date_read,
          m.associated_message_guid,
          m.associated_message_type,
          m.associated_message_emoji,
          h.id as handle_identifier
        FROM message m
        INNER JOIN chat_message_join cmj ON m.ROWID = cmj.message_id
        LEFT JOIN handle h ON m.handle_id = h.ROWID
        WHERE cmj.chat_id = ?
          AND m.is_read = 0
          AND m.is_from_me = 0
          AND m.item_type = 0
          AND m.is_finished = 1
          AND m.is_system_message = 0
        ORDER BY m.date DESC
      `);

      const messageRows = messagesStmt.all(chat.ROWID) as Array<{
        ROWID: number;
        guid: string;
        text: string | null;
        attributedBody: Buffer | null;
        date: string;
        is_from_me: number;
        handle_id: number | null;
        service: string | null;
        cache_has_attachments: number;
        item_type: number;
        is_read: number;
        date_read: string | null;
        associated_message_guid: string | null;
        associated_message_type: number | null;
        associated_message_emoji: string | null;
        handle_identifier: string | null;
      }>;

      const unreadMessages = messageRows.map((row) => {
        // Extract text (handles both plain text and attributedBody)
        const messageText = extractMessageText(row.text, row.attributedBody);

        return {
          id: String(row.ROWID),
          guid: row.guid,
          text: messageText,
          attributedBody: null,
          date: safeTimestampToNumber(row.date) ?? 0,
          isFromMe: row.is_from_me === 1,
          handleId: row.handle_id ? String(row.handle_id) : null,
          service: row.service,
          cacheHasAttachments: row.cache_has_attachments === 1,
          itemType: row.item_type,
          isRead: row.is_read === 1,
          dateRead: safeTimestampToNumber(row.date_read),
          associatedMessageGuid: row.associated_message_guid,
          associatedMessageType: row.associated_message_type,
          associatedMessageEmoji: row.associated_message_emoji,
          conversationId: String(chat.ROWID),
          chatIdentifier: chat.chat_identifier,
          displayName: chat.display_name,
          handleIdentifier: row.handle_identifier,
          contactName: row.handle_identifier
            ? lookupContactName(row.handle_identifier)
            : null,
        };
      });

      return {
        id: String(chat.ROWID),
        guid: chat.guid,
        chatIdentifier: chat.chat_identifier,
        displayName: chat.display_name,
        style: chat.style,
        serviceName: chat.service_name,
        lastReadMessageTimestamp: safeTimestampToNumber(
          chat.last_read_message_timestamp
        ),
        unreadCount: Number(chat.unread_count),
        lastActivity: safeTimestampToNumber(chat.last_activity) ?? 0,
        unreadMessages,
      };
    });

    const totalUnread = conversations.reduce(
      (sum, conv) => sum + conv.unreadCount,
      0
    );

    return {
      success: true,
      conversations,
      totalUnread,
    };
  } catch (error: any) {
    console.error("Error getting unread conversations:", error);
    return {
      success: false,
      error: error.message,
      conversations: [],
      totalUnread: 0,
    };
  } finally {
    if (db) {
      db.close();
    }
  }
});

// Get recent messages for a specific conversation
ipcMain.handle(
  "get-conversation-messages",
  async (_, chatId: string, limit: number = 5) => {
    let db: DatabaseSync | null = null;
    try {
      db = new DatabaseSync(CHAT_DB_PATH, { readOnly: true });

      // Get recent messages for this chat (regardless of read status)
      const messagesStmt = db.prepare(`
      SELECT 
        m.ROWID,
        m.guid,
        m.text,
        m.attributedBody,
        CAST(m.date AS TEXT) as date,
        m.is_from_me,
        m.handle_id,
        m.service,
        m.cache_has_attachments,
        m.item_type,
        m.is_read,
        CAST(m.date_read AS TEXT) as date_read,
        m.associated_message_guid,
        m.associated_message_type,
        m.associated_message_emoji,
        h.id as handle_identifier
      FROM message m
      INNER JOIN chat_message_join cmj ON m.ROWID = cmj.message_id
      LEFT JOIN handle h ON m.handle_id = h.ROWID
      INNER JOIN chat c ON cmj.chat_id = c.ROWID
      WHERE c.guid = ?
        AND m.item_type = 0
        AND m.is_finished = 1
        AND m.is_system_message = 0
      ORDER BY m.date DESC
      LIMIT ?
    `);

      const messageRows = messagesStmt.all(chatId, limit) as Array<{
        ROWID: number;
        guid: string;
        text: string | null;
        attributedBody: Buffer | null;
        date: string;
        is_from_me: number;
        handle_id: number | null;
        service: string | null;
        cache_has_attachments: number;
        item_type: number;
        is_read: number;
        date_read: string | null;
        associated_message_guid: string | null;
        associated_message_type: number | null;
        associated_message_emoji: string | null;
        handle_identifier: string | null;
      }>;

      // Load contacts for phone numbers in these messages
      const phoneNumbers = messageRows
        .map((m) => m.handle_identifier)
        .filter(
          (h): h is string =>
            h !== null && !h.includes("@") && isValidPhoneNumber(h)
        );

      if (phoneNumbers.length > 0) {
        const numbersToLoad = phoneNumbers.filter(
          (num) => !contactCache.has(num)
        );
        if (numbersToLoad.length > 0) {
          await loadContactsForNumbers(numbersToLoad);
        }
      }

      const messages = messageRows.map((msg) => {
        const contactName = msg.handle_identifier
          ? contactCache.get(msg.handle_identifier) || null
          : null;

        return {
          id: msg.guid,
          text: extractMessageText(msg.text, msg.attributedBody),
          date: safeTimestampToNumber(msg.date) ?? 0,
          isFromMe: msg.is_from_me === 1,
          handleIdentifier: msg.handle_identifier,
          contactName,
          service: msg.service,
          cacheHasAttachments: msg.cache_has_attachments === 1,
          isRead: msg.is_read === 1,
          dateRead: msg.date_read ? safeTimestampToNumber(msg.date_read) : null,
          associatedMessageGuid: msg.associated_message_guid,
          associatedMessageType: msg.associated_message_type,
          associatedMessageEmoji: msg.associated_message_emoji,
        };
      });

      return {
        success: true,
        messages: messages.reverse(), // Reverse to get chronological order
      };
    } catch (error: any) {
      console.error("Error getting conversation messages:", error);
      return {
        success: false,
        error: error.message,
        messages: [],
      };
    } finally {
      if (db) {
        db.close();
      }
    }
  }
);

ipcMain.handle(
  "run-agent",
  async (
    event,
    query: string,
    chatGuid: string,
    messages: Array<{
      text: string;
      isFromMe: boolean;
      handleId?: string;
      date: number;
    }>
  ) => {
    if (!query || !query.trim()) {
      return {
        success: false,
        error: "Query is required to run the agent",
      };
    }
    if (!chatGuid) {
      return {
        success: false,
        error: "Conversation GUID is required",
      };
    }

    try {
      const context = await buildAgentContext(chatGuid, messages);
      const agentResult = await runAgentStream(query, context);
      const streamId = randomUUID();
      const webContents = event.sender;
      const DEBUG = process.env.TEXTREME_AGENT_DEBUG === "1";

      if (DEBUG) {
        console.log(
          `[agent] run-agent invoked (streamId=${streamId}) for conversation=${chatGuid}`
        );
      }

      const channel = `agent-stream:${streamId}`;

      setImmediate(async () => {
        try {
          for await (const agentEvent of agentResult.fullStream) {
            if (webContents.isDestroyed()) {
              break;
            }
            webContents.send(channel, agentEvent);
          }

          const finalOutput = await agentResult.getFinalOutput();
          if (!webContents.isDestroyed()) {
            if (DEBUG) {
              console.log(
                `[agent] Stream complete (streamId=${streamId}), delivering final output`
              );
            }
            webContents.send(channel, {
              type: "complete",
              finalOutput,
            });
          }
        } catch (streamError: any) {
          if (DEBUG) {
            console.error(
              `[agent] Stream error (streamId=${streamId}):`,
              streamError
            );
          }
          if (!webContents.isDestroyed()) {
            webContents.send(channel, {
              type: "error",
              error:
                streamError instanceof Error
                  ? streamError.message
                  : String(streamError),
            });
          }
        }
      });

      return {
        success: true,
        streamId,
      };
    } catch (error: any) {
      console.error("Error running agent:", error);
      return {
        success: false,
        error: error instanceof Error ? error.message : "Failed to run agent",
      };
    }
  }
);

/**
 * Generate text completions using Vercel AI SDK with structured output
 */
async function generateCompletionsWithAI(
  lastMessages: Array<{ text: string | null; isFromMe: boolean }>,
  draft: string
): Promise<string[]> {
  // Build conversation context
  const contextLines = lastMessages
    .slice(-10) // Last 10 messages for context
    .map((msg) => {
      const sender = msg.isFromMe ? "You" : "Them";
      const text = msg.text || "[No text]";
      return `${sender}: ${text}`;
    });

  const context = contextLines.join("\n");

  const systemPrompt = `You are an autocomplete system for iMessage. Given a conversation context and partial text the user is typing, predict 3 different ways the user might complete their message.

Rules:
- Generate ONLY the continuation text that comes AFTER the user's partial input
- Do NOT repeat the user's input text - only provide what comes next
- Ensure proper grammar: add punctuation (?, !, .) if the draft needs it before continuing
- Use proper capitalization: lowercase if continuing same sentence, uppercase if starting new sentence
- Match the user's style and tone from the conversation
- Keep completions short and natural (typically a few words to one sentence)
- NO EMOJIS - plain text only
- The continuation should flow naturally from where the user stopped typing
- Provide diverse options (different tones, lengths, or approaches)

Examples:
If user typed: "I don't care about"
Good completions: ["your opinion", "what they think", "that right now"]

If user typed: "who asked"
Good completions: ["?", " lol", "? That's totally unnecessary"]

If user typed: "that's"
Good completions: [" so expensive", " ridiculous", " way too much"]

Bad completions: ["I don't care about your opinion", "Who asked lol", "That's expensive"]`;

  const userPrompt = `Conversation context:
${context}

User is typing: "${draft}"

Generate 3 different ways to complete this message. Return ONLY the text that continues after "${draft}".`;

  try {
    console.log("Making request to OpenAI");
    const { object } = await generateObject({
      model: openai("gpt-5-nano"),
      schema: z.object({
        completions: z.array(z.string()).length(3),
      }),
      system: systemPrompt,
      prompt: userPrompt,
      temperature: 1.0,
    });

    return object.completions;
  } catch (error) {
    console.error("AI SDK error:", error);
    throw error;
  }
}

// IPC handler for generating autocomplete suggestions with messages from UI
ipcMain.handle(
  "generate-completions",
  async (
    _event,
    messages: Array<{ text: string | null; isFromMe: boolean }>,
    draft: string
  ) => {
    try {
      const completions = await generateCompletionsWithAI(messages, draft);

      return {
        success: true,
        suggestions: completions,
      };
    } catch (error: any) {
      console.error("Error generating completions:", error);
      return {
        success: false,
        suggestions: [],
        error: error.message || "Failed to generate completions",
      };
    }
  }
);

// Helper function to escape AppleScript strings
function escapeAppleScriptString(str: string): string {
  // Replace backslashes first, then quotes
  return str.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

// Helper function to execute AppleScript using shell command with timeout
async function executeAppleScript(
  script: string,
  timeoutMs: number = 10000
): Promise<void> {
  // Escape the script for shell: replace single quotes with '\'' and wrap in single quotes
  // This ensures the script is safely passed to the shell
  const escapedScript = script.replace(/'/g, "'\\''");
  // Use printf to pipe the script to osascript, which handles newlines and special chars better
  const command = `printf '%s\n' '${escapedScript}' | osascript`;

  console.log("[DEBUG] executeAppleScript - Command length:", command.length);
  console.log(
    "[DEBUG] executeAppleScript - Script preview (first 200 chars):",
    script.substring(0, 200)
  );

  // Create a promise that times out
  const timeoutPromise = new Promise<never>((_, reject) => {
    setTimeout(
      () =>
        reject(
          new Error(`AppleScript execution timed out after ${timeoutMs}ms`)
        ),
      timeoutMs
    );
  });

  try {
    const { stdout, stderr } = await Promise.race([
      execAsync(command),
      timeoutPromise,
    ]);

    console.log("[DEBUG] executeAppleScript - stdout:", stdout);
    console.log("[DEBUG] executeAppleScript - stderr:", stderr);

    // Some AppleScript errors are expected (like Messages app warnings)
    // Only throw if it's a real error
    if (
      stderr &&
      !stderr.includes("Messages") &&
      !stderr.includes("execution error")
    ) {
      console.error("[DEBUG] executeAppleScript - Throwing error:", stderr);
      throw new Error(stderr);
    }
  } catch (error) {
    console.error("[DEBUG] executeAppleScript - Error:", error);
    throw error;
  }
}

// Helper function to mark conversation as read by clicking on it in Messages
async function markConversationAsReadViaClick(
  recipient: string
): Promise<void> {
  try {
    const escapedRecipient = escapeAppleScriptString(recipient);

    const appleScript = `
set recipient to "${escapedRecipient}"

set h to ""

-- Try to find contact by name first
try
  tell application "Contacts"
    set p to first person whose name is recipient
    if (count of phones of p) > 0 then
      set h to value of first phone of p
    else if (count of emails of p) > 0 then
      set h to value of first email of p
    end if
  end tell
on error
  -- If not found as contact name, assume recipient is already phone/email
  set h to recipient
end try

if h is "" then
  set h to recipient
end if

-- Activate Messages and click on the conversation to mark it as read
tell application "Messages"
  activate
  delay 0.5
end tell

tell application "System Events"
  tell process "Messages"
    -- Wait for Messages window to be ready
    repeat until exists window 1
      delay 0.1
    end repeat
    
    -- Try to find and click the conversation in the sidebar
    try
      -- Look for the conversation row that contains the recipient identifier
      set conversationRows to rows of table 1 of scroll area 1 of splitter group 1 of window 1
      repeat with aRow in conversationRows
        try
          set rowText to value of static text 1 of aRow
          if rowText contains h or rowText contains recipient then
            -- Click on the row to open the conversation and mark as read
            click aRow
            delay 0.2
            exit repeat
          end if
        end try
      end repeat
    on error errMsg
      -- If UI structure is different, try alternative approach
      log "Could not find conversation row: " & errMsg
    end try
  end tell
end tell

-- Hide Messages app again
tell application "System Events"
  set visible of process "Messages" to false
end tell

delay 0.3
`.trim();

    await executeAppleScript(appleScript);

    console.log(`Marked conversation as read: ${recipient}`);
  } catch (error: any) {
    console.error("Error marking conversation as read via click:", error);
    // Don't throw - this is a best-effort operation
  }
}

// AppleScript execution handler
ipcMain.handle(
  "send-imessage",
  async (_event, recipient: string, messageText: string) => {
    console.log("[DEBUG] send-imessage handler called:", {
      recipient,
      messageText,
      recipientLength: recipient?.length || 0,
      messageLength: messageText?.length || 0,
      recipientType: typeof recipient,
      messageTextType: typeof messageText,
    });

    try {
      if (!recipient || recipient.trim() === "") {
        console.error("[DEBUG] send-imessage - Empty recipient!");
        return {
          success: false,
          error: "Recipient is empty",
        };
      }

      if (!messageText || messageText.trim() === "") {
        console.error("[DEBUG] send-imessage - Empty messageText!");
        return {
          success: false,
          error: "Message text is empty",
        };
      }

      // Escape strings for AppleScript
      const escapedRecipient = escapeAppleScriptString(recipient);
      const escapedMessage = escapeAppleScriptString(messageText);

      console.log("[DEBUG] send-imessage - After escaping:", {
        escapedRecipient,
        escapedMessage,
        escapedRecipientLength: escapedRecipient.length,
        escapedMessageLength: escapedMessage.length,
      });

      // Build AppleScript with proper escaping
      // Use AppleScript's quoted form for safer string handling

      const appleScript = `
set recipient to "${escapedRecipient}"
set messageText to "${escapedMessage}"

set h to ""

-- Try to find contact by name first
try
  tell application "Contacts"
    set p to first person whose name is recipient
    if (count of phones of p) > 0 then
      set h to value of first phone of p
    else if (count of emails of p) > 0 then
      set h to value of first email of p
    end if
  end tell
on error
  -- If not found as contact name, assume recipient is already phone/email
  set h to recipient
end try

if h is "" then
  error "Recipient has no phone or email in Contacts."
end if

-- Ensure Messages is running and responsive
tell application "Messages"
  -- Briefly activate to ensure it's responsive
  activate
  delay 0.1
end tell

-- Hide Messages immediately
tell application "System Events"
  set visible of process "Messages" to false
end tell

-- Send message
tell application "Messages"
  set targetService to 1st service whose service type = iMessage
  set targetBuddy to buddy h of targetService
  send messageText to targetBuddy
end tell

-- Small delay to ensure message is sent
delay 0.2
`.trim();

      // Execute using spawn with stdin for reliable script execution
      console.log("[DEBUG] send-imessage - About to execute AppleScript");
      await executeAppleScript(appleScript, 5000); // 5 second timeout
      console.log("[DEBUG] send-imessage - AppleScript executed successfully");

      // After successfully sending, mark the conversation as read (non-blocking)
      console.log("[DEBUG] send-imessage - Marking conversation as read");
      markConversationAsReadViaClick(recipient).catch((error) => {
        console.log(
          "[DEBUG] send-imessage - Failed to mark as read (non-critical):",
          error
        );
      });
      console.log(
        "[DEBUG] send-imessage - Initiated mark-as-read (non-blocking)"
      );

      return {
        success: true,
        message: "Message sent successfully!",
      };
    } catch (error) {
      console.error("[DEBUG] send-imessage - AppleScript error:", error);
      console.error("[DEBUG] send-imessage - Error details:", {
        errorMessage: error instanceof Error ? error.message : String(error),
        errorStack: error instanceof Error ? error.stack : undefined,
        recipient,
        messageText,
      });
      return {
        success: false,
        error:
          error instanceof Error ? error.message : "Unknown error occurred",
      };
    }
  }
);
