import {
  app,
  BrowserWindow,
  ipcMain,
  shell,
  systemPreferences,
  screen,
} from "electron";
import path from "path";
import { DatabaseSync } from "node:sqlite";
import os from "os";
import { spawn, exec } from "child_process";
import { promisify } from "util";

const execAsync = promisify(exec);

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Vite
// plugin that tells the Electron app where to look for the Vite-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_VITE_DEV_SERVER_URL: string;
declare const MAIN_WINDOW_VITE_NAME: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require("electron-squirrel-startup")) {
  app.quit();
}

const CHAT_DB_PATH = path.join(os.homedir(), "Library/Messages/chat.db");

// Contact cache to avoid re-lookups
const contactCache = new Map<string, string>(); // phone number -> contact name
let contactMap: Map<string, string> | null = null;
let contactMapLoading = false;

// Store the original bottom position to keep it fixed during resizes
let originalBottomY: number | null = null;

const createWindow = (): void => {
  // Get screen dimensions
  const { width: screenWidth, height: screenHeight } = screen.getPrimaryDisplay().workAreaSize;
  
  const windowWidth = 600;
  const windowHeight = 200;
  const bottomMargin = 2; // Distance from bottom of screen
  
  // Calculate position: centered horizontally, at bottom vertically
  const x = Math.floor((screenWidth - windowWidth) / 2);
  const y = screenHeight - windowHeight - bottomMargin;
  
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    width: windowWidth,
    height: windowHeight,
    x: x,
    y: y,
    frame: false,
    transparent: true, // Remove backdrop shadow
    hasShadow: false, // Remove window shadow on macOS
    backgroundColor: '#00000000', // Fully transparent background
    webPreferences: {
      preload: path.join(__dirname, "preload.js"),
      nodeIntegration: false,
      contextIsolation: true,
    },
  });

  // and load the index.html of the app.
  if (MAIN_WINDOW_VITE_DEV_SERVER_URL) {
    mainWindow.loadURL(MAIN_WINDOW_VITE_DEV_SERVER_URL);
  } else {
    mainWindow.loadFile(
      path.join(__dirname, `../renderer/${MAIN_WINDOW_VITE_NAME}/index.html`)
    );
  }

  // Store the original bottom position once window is ready
  mainWindow.once('ready-to-show', () => {
    const cb = mainWindow.getContentBounds();
    originalBottomY = cb.y + cb.height;
  });

  // Open the DevTools.
  if (!app.isPackaged) {
    mainWindow.webContents.openDevTools();
  }
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on("ready", createWindow);

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on("window-all-closed", () => {
  if (process.platform !== "darwin") {
    app.quit();
  }
});

app.on("activate", () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.

/**
 * Close window handler
 */
ipcMain.on("close-window", () => {
  const window = BrowserWindow.getFocusedWindow();
  if (window) {
    window.close();
  }
});

/**
 * Resize window handler — expand upward while keeping bottom fixed
 */
ipcMain.on("resize-window", (event, newHeight: number) => {
  const win = BrowserWindow.fromWebContents(event.sender);
  if (!win) return;

  // Work in content-space so transparent/frame/shadow don't skew math
  const cb = win.getContentBounds();

  // Device-pixel alignment to avoid 1px jitter on scaled displays
  const scale =
    screen.getDisplayMatching(cb).scaleFactor ||
    screen.getPrimaryDisplay().scaleFactor ||
    1;
  const align = (v: number) => Math.round(v * scale) / scale;

  // Use the stored original bottom position, or calculate it if not set
  if (originalBottomY === null) {
    originalBottomY = cb.y + cb.height;
  }

  // Always anchor to the original bottom position
  const targetY = align(originalBottomY - newHeight);

  win.setContentBounds(
    {
      x: align(cb.x),
      y: targetY,
      width: align(cb.width),
      height: align(newHeight),
    },
    /* animate */ true
  );
});


/**
 * Check if we have Full Disk Access to read the iMessage database
 */
ipcMain.handle("check-database-access", async () => {
  try {
    const fs = require("fs");

    // Check if file exists and is readable
    if (!fs.existsSync(CHAT_DB_PATH)) {
      return {
        hasAccess: false,
        path: CHAT_DB_PATH,
        error: "Database file not found",
      };
    }

    // Try to get file stats to verify read access
    const stats = fs.statSync(CHAT_DB_PATH);

    return {
      hasAccess: true,
      path: CHAT_DB_PATH,
      fileSize: stats.size,
      lastModified: stats.mtime,
    };
  } catch (error: any) {
    return {
      hasAccess: false,
      path: CHAT_DB_PATH,
      error: error.message,
    };
  }
});

/**
 * Get database statistics (file size, last modified, etc.)
 */
ipcMain.handle("get-database-stats", async () => {
  try {
    const fs = require("fs");
    const stats = fs.statSync(CHAT_DB_PATH);

    return {
      success: true,
      fileSize: stats.size,
      fileSizeMB: (stats.size / (1024 * 1024)).toFixed(2),
      lastModified: stats.mtime.toISOString(),
      path: CHAT_DB_PATH,
    };
  } catch (error: any) {
    return {
      success: false,
      error: error.message,
    };
  }
});

/**
 * Get list of tables in the database
 */
ipcMain.handle("get-database-tables", async () => {
  let db: DatabaseSync | null = null;
  try {
    db = new DatabaseSync(CHAT_DB_PATH, { readOnly: true });

    const tablesQuery = db.prepare(`
      SELECT name, type 
      FROM sqlite_master 
      WHERE type IN ('table', 'view')
      ORDER BY name
    `);

    const tables = tablesQuery.all() as Array<{ name: string; type: string }>;

    return {
      success: true,
      tables,
      totalCount: tables.length,
    };
  } catch (error: any) {
    return {
      success: false,
      error: error.message,
      tables: [],
      totalCount: 0,
    };
  } finally {
    if (db) {
      db.close();
    }
  }
});

/**
 * Open System Preferences to Full Disk Access pane
 */
ipcMain.handle("open-system-preferences", async () => {
  try {
    // Open the Full Disk Access settings pane
    shell.openExternal(
      "x-apple.systempreferences:com.apple.preference.security?Privacy_AllFiles"
    );
    return { success: true };
  } catch (error: any) {
    return {
      success: false,
      error: error.message,
    };
  }
});

/**
 * Helper function to safely convert Apple timestamp (which can be very large) to number
 * Apple timestamps are in nanoseconds since 2001-01-01
 */
function safeTimestampToNumber(timestamp: any): number | null {
  if (timestamp === null || timestamp === undefined) {
    return null;
  }

  // If it's already a number and within safe range, return it
  if (typeof timestamp === "number") {
    return timestamp;
  }

  // If it's a string (from CAST AS TEXT), parse it
  if (typeof timestamp === "string") {
    try {
      // Use BigInt to handle large numbers, then convert to regular number
      const bigIntValue = BigInt(timestamp);
      // Convert to number (may lose precision but that's okay for timestamps)
      return Number(bigIntValue);
    } catch {
      return null;
    }
  }

  // Try parsing as BigInt if it's some other type
  try {
    const bigIntValue = BigInt(timestamp);
    return Number(bigIntValue);
  } catch {
    // Fallback to direct conversion
    return Number(timestamp);
  }
}

/**
 * Check if a text chunk looks like binary metadata/artifacts
 */
function isBinaryArtifact(chunk: string): boolean {
  const lower = chunk.toLowerCase();

  // Filter out NSObject-related patterns
  if (
    lower.includes("nsattributedstring") ||
    lower.includes("nsobject") ||
    lower.includes("nsdictionary") ||
    lower.includes("nsmutable") ||
    lower.includes("nsstring") ||
    lower.includes("nsnumber") ||
    lower.includes("nsvalue") ||
    lower.includes("streamtyped") ||
    lower.includes("__kim")
  ) {
    return true;
  }

  // Filter out binary plist markers (X$version, Y$archiver, T$top, etc.)
  if (/\$version|\$archiver|\$top|\$objects|X\$|Y\$|T\$|Z\$/.test(chunk)) {
    return true;
  }

  // Filter out NS.rangeval, NS.special, NS.location patterns
  if (/NS\.(rangeval|special|location|objects|classname)/i.test(chunk)) {
    return true;
  }

  // Filter out patterns that look like binary metadata (containing $ and version/archiver)
  if (
    chunk.includes("$") &&
    (lower.includes("version") ||
      lower.includes("archiver") ||
      lower.includes("objects"))
  ) {
    return true;
  }

  // Filter out pure numbers
  if (/^\d+$/.test(chunk)) {
    return true;
  }

  return false;
}

/**
 * Remove binary artifact patterns from text, even when embedded in longer strings
 */
function removeBinaryArtifacts(text: string): string {
  let cleaned = text;

  // Remove concatenated patterns like "X$versionY$archiverT$topX$objects" (no spaces between)
  // This catches patterns where multiple $ markers are concatenated together
  cleaned = cleaned.replace(
    /[XYZ]\$[a-zA-Z]+[XYZ]\$[a-zA-Z]+[TZ]\$[a-zA-Z]+[XYZ]\$[a-zA-Z]+/g,
    ""
  );

  // Remove individual binary plist patterns (X$version, Y$archiver, T$top, Z$objects, etc.)
  cleaned = cleaned.replace(/[XYZ]\$[a-zA-Z]+/g, "");
  cleaned = cleaned.replace(/T\$[a-zA-Z]+/g, "");
  cleaned = cleaned.replace(/\$[a-zA-Z]+/g, "");

  // Remove NS. patterns (NS.rangeval, NS.special, NS.location, etc.)
  // Also handle cases like "NS.rangeval.locationZNS.special" where Z might be between
  cleaned = cleaned.replace(/NS\.[a-zA-Z]+/g, "");
  cleaned = cleaned.replace(/[A-Z]NS\.[a-zA-Z]+/g, ""); // Handle ZNS.special, etc.

  // Remove patterns with $ followed by version/archiver/objects/top (with or without surrounding chars)
  cleaned = cleaned.replace(/\S*\$version\S*/gi, "");
  cleaned = cleaned.replace(/\S*\$archiver\S*/gi, "");
  cleaned = cleaned.replace(/\S*\$objects\S*/gi, "");
  cleaned = cleaned.replace(/\S*\$top\S*/gi, "");

  // Remove NSObject class names (with word boundaries)
  cleaned = cleaned.replace(
    /\bNS(AttributedString|Object|Dictionary|Mutable|String|Number|Value|Array|Data)\b/gi,
    ""
  );

  // Remove streamtyped
  cleaned = cleaned.replace(/\bstreamtyped\b/gi, "");

  // Remove __kIM patterns
  cleaned = cleaned.replace(/\b__kIM\w+\b/gi, "");

  // Remove patterns like "rangeval.location" or standalone metadata words
  cleaned = cleaned.replace(
    /\b(rangeval|special|location|objects|classname|archiver|version)\.[a-zA-Z]+\b/gi,
    ""
  );

  // Remove patterns like "locationZNS" where a metadata word is concatenated with NS
  cleaned = cleaned.replace(
    /\b(rangeval|special|location|objects|classname)[A-Z]+NS\b/gi,
    ""
  );

  // Remove standalone metadata words that might appear (rangeval, special, etc.)
  cleaned = cleaned.replace(
    /\b(rangeval|special|location|objects|classname)\b/gi,
    ""
  );

  // Remove any word that contains both a metadata term and NS (like "locationZNS")
  cleaned = cleaned.replace(
    /\b\w*(rangeval|special|location|objects|classname)\w*NS\w*\b/gi,
    ""
  );
  cleaned = cleaned.replace(
    /\b\w*NS\w*(rangeval|special|location|objects|classname)\w*\b/gi,
    ""
  );

  // Clean up multiple spaces and periods/spaces
  cleaned = cleaned.replace(/\s+/g, " ");
  cleaned = cleaned.replace(/\.\s*\./g, "."); // Remove double periods
  cleaned = cleaned.trim();

  return cleaned;
}

/**
 * Helper function to extract text from a message
 * Handles both plain text field and attributedBody binary data
 * Based on research from imessage-db-exploration.md and SQL exploration
 *
 * The attributedBody format stores text as readable UTF-8 strings embedded in the binary data.
 */
function extractMessageText(
  text: string | null,
  attributedBody: Buffer | null
): string | null {
  // If plain text is available, use it
  if (text) {
    return text;
  }

  // Otherwise, try to extract from attributedBody
  if (!attributedBody) {
    return null;
  }

  try {
    const textChunks: string[] = [];

    // Convert to Buffer if it's not already (node-sqlite returns Uint8Array)
    const buffer = Buffer.isBuffer(attributedBody)
      ? attributedBody
      : Buffer.from(attributedBody);

    // Scan the entire buffer sequentially for readable ASCII text sequences
    // Look for sequences of printable ASCII characters (32-126)
    let textStart = -1;
    let textLength = 0;

    for (let i = 0; i < buffer.length; i++) {
      const byte = buffer[i];
      // Only printable ASCII for now (32-126)
      const isPrintable = byte >= 32 && byte <= 126;

      if (isPrintable) {
        if (textStart === -1) {
          textStart = i;
        }
        textLength++;
      } else {
        // End of printable sequence - extract if long enough (at least 3 chars)
        if (textLength >= 3 && textStart !== -1) {
          try {
            const chunk = buffer.subarray(textStart, textStart + textLength);
            const decoded = chunk.toString("ascii");
            // Must contain letters and be meaningful
            if (decoded.length >= 3 && /[A-Za-z]/.test(decoded)) {
              const trimmed = decoded.trim();
              // Filter out binary artifacts
              if (!isBinaryArtifact(trimmed)) {
                textChunks.push(trimmed);
              }
            }
          } catch (e) {
            // Skip invalid sequences
          }
        }
        textStart = -1;
        textLength = 0;
      }
    }

    // Handle text that extends to end of buffer
    if (textLength >= 3 && textStart !== -1) {
      try {
        const chunk = buffer.subarray(textStart, textStart + textLength);
        const decoded = chunk.toString("ascii");
        if (decoded.length >= 3 && /[A-Za-z]/.test(decoded)) {
          const trimmed = decoded.trim();
          if (!isBinaryArtifact(trimmed)) {
            textChunks.push(trimmed);
          }
        }
      } catch (e) {
        // Skip invalid sequences
      }
    }

    if (textChunks.length === 0) {
      return null;
    }

    // Join chunks, removing duplicates and cleaning up
    // Sort by length (longest first) to prioritize actual message content
    const sortedChunks = [...new Set(textChunks)].sort(
      (a, b) => b.length - a.length
    );

    // Take the longest chunks (likely the actual message)
    const topChunks = sortedChunks
      .slice(0, 3)
      .filter((c) => c.length >= 3 && !isBinaryArtifact(c));
    let result = topChunks.join(" ");

    // If we didn't get good results, try all chunks (but still filter artifacts)
    if (result.length < 5) {
      result = sortedChunks.filter((c) => !isBinaryArtifact(c)).join(" ");
    }

    // Final cleanup - remove any remaining binary artifacts that might have slipped through
    // First, remove artifact patterns from the entire string
    result = removeBinaryArtifacts(result);

    // Then split by spaces and filter out individual words that are artifacts
    const words = result.split(/\s+/).filter((word) => {
      // Keep words that don't look like binary artifacts
      return !isBinaryArtifact(word) && word.length > 0;
    });

    result = words
      .join(" ")
      .replace(/\s+/g, " ") // Multiple spaces to single
      .replace(/\n{3,}/g, "\n\n") // Max 2 consecutive newlines
      .trim();

    // Must have meaningful content
    if (result.length < 2 || !/[A-Za-z]/.test(result)) {
      return null;
    }

    return result;
  } catch (error) {
    console.error("Error extracting text from attributedBody:", error);
    return null;
  }
}

/**
 * Normalize phone number for matching (remove formatting, keep + and digits)
 */
function normalizePhoneNumber(phone: string): string {
  // Remove all non-digit characters except +
  return phone.replace(/[^\d+]/g, "");
}

/**
 * Load all contacts from Contacts app via Swift CLI
 * Uses native Contacts framework - much faster than AppleScript
 */
async function loadContactMap(): Promise<Map<string, string>> {
  // Return existing map if already loaded
  if (contactMap) {
    return contactMap;
  }

  // If already loading, wait a bit and return empty map
  if (contactMapLoading) {
    return new Map();
  }

  contactMapLoading = true;

  try {
    console.log("Loading contacts from Contacts app...");

    // Path to the contacts_dump binary (should be copied by build script)
    const binaryPath = app.isPackaged
      ? path.join(process.resourcesPath, "contacts_dump")
      : path.join(__dirname, "../../contacts_dump");

    // Execute the Swift binary
    const proc = spawn(binaryPath, [], {
      stdio: ["pipe", "pipe", "pipe"],
    });

    let stdout = "";
    let stderr = "";

    proc.stdout.on("data", (data) => {
      stdout += data.toString();
    });

    proc.stderr.on("data", (data) => {
      stderr += data.toString();
    });

    await new Promise<void>((resolve, reject) => {
      proc.on("close", (code) => {
        if (code === 0) {
          resolve();
        } else {
          reject(
            new Error(`contacts_dump exited with code ${code}: ${stderr}`)
          );
        }
      });

      proc.on("error", (err) => {
        reject(err);
      });
    });

    // Parse JSON output
    const jsonData = stdout.trim();
    const map = new Map<string, string>();

    type PersonEntry = { name: string; phones: { numberRaw: string }[] };
    const contacts: PersonEntry[] = JSON.parse(jsonData);

    console.log(`Loaded ${contacts.length} contacts from Contacts app`);

    // Build the map with multiple normalized formats for each phone number
    for (const contact of contacts) {
      const name = contact.name.trim();
      if (!name || name === "Unknown") continue;

      for (const phoneEntry of contact.phones) {
        const phoneRaw = phoneEntry.numberRaw;
        if (!phoneRaw) continue;

        const normalized = normalizePhoneNumber(phoneRaw);

        // Store multiple formats for phone numbers
        map.set(normalized, name);
        if (normalized.startsWith("+")) {
          map.set(normalized.slice(1), name);
        }
        if (normalized.length >= 10) {
          map.set(normalized.slice(-10), name);
        }
        if (normalized.length >= 7) {
          map.set(normalized.slice(-7), name);
        }
      }
    }

    console.log(`Built contact map with ${map.size} phone number mappings`);
    contactMap = map;
    return map;
  } catch (error: any) {
    console.error("Error loading contacts:", error);
    console.error("Error details:", {
      message: error.message,
      code: error.code,
      signal: error.signal,
    });
    // Return empty map on error
    contactMap = new Map();
    return contactMap;
  } finally {
    contactMapLoading = false;
  }
}

/**
 * Load contacts for specific phone numbers
 * Loads the full contact map once, then uses it for lookups
 */
async function loadContactsForNumbers(phoneNumbers: string[]): Promise<void> {
  // If map is already loaded, we don't need to do anything
  if (contactMap) {
    return;
  }

  // Load the full contact map
  const map = await loadContactMap();

  // Cache the lookups
  for (const phone of phoneNumbers) {
    const name = lookupContactName(phone);
    if (name) {
      contactCache.set(phone, name);
    }
  }
}

/**
 * Check if a phone number is valid (not a short code or invalid)
 */
function isValidPhoneNumber(phone: string): boolean {
  const normalized = normalizePhoneNumber(phone);
  // Must be at least 10 digits (US phone number) or have + and be reasonable length
  if (normalized.startsWith("+")) {
    // International: +1XXXXXXXXXX (11 chars minimum) or longer
    return normalized.length >= 11;
  }
  // Domestic: at least 10 digits
  return normalized.length >= 10;
}

/**
 * Look up contact name from phone number or email
 * Uses pre-loaded contact map (must be loaded separately)
 */
function lookupContactName(identifier: string): string | null {
  if (!identifier) return null;

  // Check cache first
  if (contactCache.has(identifier)) {
    return contactCache.get(identifier) || null;
  }

  // Email addresses - return as is for now
  if (identifier.includes("@")) {
    return null;
  }

  // Phone number - check contact map
  if (!contactMap) {
    return null;
  }

  // Try various normalized formats
  const formats = [identifier, normalizePhoneNumber(identifier)];

  const normalized = normalizePhoneNumber(identifier);
  if (normalized.startsWith("+")) {
    formats.push(normalized.slice(1));
  }
  if (normalized.length >= 10) {
    formats.push(normalized.slice(-10));
  }
  if (normalized.length >= 7) {
    formats.push(normalized.slice(-7));
  }

  for (const format of formats) {
    const name = contactMap.get(format);
    if (name) {
      // Cache it
      contactCache.set(identifier, name);
      return name;
    }
  }

  return null;
}

/**
 * Get all unread messages
 * Returns flat list of unread messages ordered by date (newest first)
 */
ipcMain.handle("get-unread-messages", async (_, limit?: number) => {
  let db: DatabaseSync | null = null;
  try {
    db = new DatabaseSync(CHAT_DB_PATH, { readOnly: true });

    // Query for unread messages with related info
    // We'll get the chat identifier and display name for each message
    const query = `
      SELECT 
        m.ROWID,
        m.guid,
        m.text,
        m.attributedBody,
        CAST(m.date AS TEXT) as date,
        m.is_from_me,
        m.handle_id,
        m.service,
        m.cache_has_attachments,
        m.item_type,
        m.is_read,
        CAST(m.date_read AS TEXT) as date_read,
        m.associated_message_guid,
        m.associated_message_type,
        m.associated_message_emoji,
        c.ROWID as chat_id,
        c.chat_identifier,
        c.display_name,
        h.id as handle_identifier
      FROM message m
      INNER JOIN chat_message_join cmj ON m.ROWID = cmj.message_id
      INNER JOIN chat c ON cmj.chat_id = c.ROWID
      LEFT JOIN handle h ON m.handle_id = h.ROWID
      WHERE m.is_read = 0 
        AND m.is_from_me = 0
        AND m.item_type = 0
        AND m.is_finished = 1
        AND m.is_system_message = 0
      ORDER BY m.date DESC
      ${limit ? `LIMIT ${limit}` : ""}
    `;

    const stmt = db.prepare(query);
    const rows = stmt.all() as Array<{
      ROWID: number;
      guid: string;
      text: string | null;
      attributedBody: Buffer | null;
      date: string;
      is_from_me: number;
      handle_id: number | null;
      service: string | null;
      cache_has_attachments: number;
      item_type: number;
      is_read: number;
      date_read: string | null;
      associated_message_guid: string | null;
      associated_message_type: number | null;
      associated_message_emoji: string | null;
      chat_id: number;
      chat_identifier: string;
      display_name: string | null;
      handle_identifier: string | null;
    }>;

    // Collect unique phone numbers from all unread messages
    const phoneNumberSet = new Set<string>();
    const phoneNumberList: Array<{ phone: string; date: number }> = [];

    for (const row of rows) {
      if (row.handle_identifier && !row.handle_identifier.includes("@")) {
        if (isValidPhoneNumber(row.handle_identifier)) {
          phoneNumberSet.add(row.handle_identifier);
          phoneNumberList.push({
            phone: row.handle_identifier,
            date: safeTimestampToNumber(row.date) ?? 0,
          });
        }
      }
    }

    console.log(`Found ${phoneNumberList.length} unique valid phone numbers`);

    // Load contacts only for the specific phone numbers we need
    const numbersToLoad = phoneNumberList
      .filter((item) => !contactCache.has(item.phone))
      .map((item) => item.phone);

    if (numbersToLoad.length > 0) {
      console.log(
        `Loading contacts for ${numbersToLoad.length} new phone numbers...`
      );
      await loadContactsForNumbers(numbersToLoad);
    }

    const messages = rows.map((row) => {
      // Extract text (handles both plain text and attributedBody)
      const messageText = extractMessageText(row.text, row.attributedBody);

      return {
        id: String(row.ROWID),
        guid: row.guid,
        text: messageText,
        attributedBody: null, // Don't send binary data to renderer
        date: safeTimestampToNumber(row.date) ?? 0,
        isFromMe: row.is_from_me === 1,
        handleId: row.handle_id ? String(row.handle_id) : null,
        service: row.service,
        cacheHasAttachments: row.cache_has_attachments === 1,
        itemType: row.item_type,
        isRead: row.is_read === 1,
        dateRead: safeTimestampToNumber(row.date_read),
        associatedMessageGuid: row.associated_message_guid,
        associatedMessageType: row.associated_message_type,
        associatedMessageEmoji: row.associated_message_emoji,
        conversationId: String(row.chat_id),
        // Additional fields for display
        chatIdentifier: row.chat_identifier,
        displayName: row.display_name,
        handleIdentifier: row.handle_identifier,
        // Look up contact name (synchronous now - map is pre-loaded)
        contactName: row.handle_identifier
          ? lookupContactName(row.handle_identifier)
          : null,
      };
    });

    return {
      success: true,
      messages,
      count: messages.length,
    };
  } catch (error: any) {
    console.error("Error getting unread messages:", error);
    return {
      success: false,
      error: error.message,
      messages: [],
      count: 0,
    };
  } finally {
    if (db) {
      db.close();
    }
  }
});

/**
 * Get unread messages grouped by conversation/chat
 * Returns conversations with their unread messages
 */
ipcMain.handle("get-unread-conversations", async () => {
  let db: DatabaseSync | null = null;
  try {
    db = new DatabaseSync(CHAT_DB_PATH, { readOnly: true });

    // First, get all chats with unread counts
    const chatStmt = db.prepare(`
      SELECT 
        c.ROWID,
        c.guid,
        c.chat_identifier,
        c.display_name,
        c.style,
        c.service_name,
        CAST(c.last_read_message_timestamp AS TEXT) as last_read_message_timestamp,
        COUNT(DISTINCT m.ROWID) as unread_count,
        CAST(MAX(m.date) AS TEXT) as last_activity
      FROM chat c
      INNER JOIN chat_message_join cmj ON c.ROWID = cmj.chat_id
      INNER JOIN message m ON cmj.message_id = m.ROWID
      WHERE m.is_read = 0
        AND m.is_from_me = 0
        AND m.item_type = 0
        AND m.is_finished = 1
        AND m.is_system_message = 0
      GROUP BY c.ROWID
      ORDER BY MAX(m.date) DESC
    `);

    const chats = chatStmt.all() as Array<{
      ROWID: number;
      guid: string;
      chat_identifier: string;
      display_name: string | null;
      style: number | null;
      service_name: string | null;
      last_read_message_timestamp: string | null;
      unread_count: number;
      last_activity: string;
    }>;

    // Pre-load contacts for all unread messages
    const phoneNumberSet = new Set<string>();
    const phoneNumberList: Array<{ phone: string; date: number }> = [];

    // Get all unread messages to collect phone numbers
    const allMessagesStmt = db.prepare(`
      SELECT DISTINCT
        h.id as handle_identifier,
        CAST(MAX(m.date) AS TEXT) as latest_date
      FROM message m
      INNER JOIN chat_message_join cmj ON m.ROWID = cmj.message_id
      LEFT JOIN handle h ON m.handle_id = h.ROWID
      WHERE m.is_read = 0
        AND m.is_from_me = 0
        AND m.item_type = 0
        AND m.is_finished = 1
        AND m.is_system_message = 0
        AND h.id IS NOT NULL
      GROUP BY h.id
      ORDER BY MAX(m.date) DESC
    `);

    const phoneRows = allMessagesStmt.all() as Array<{
      handle_identifier: string;
      latest_date: string;
    }>;

    for (const row of phoneRows) {
      if (row.handle_identifier && !row.handle_identifier.includes("@")) {
        // Only include valid phone numbers
        if (isValidPhoneNumber(row.handle_identifier)) {
          phoneNumberSet.add(row.handle_identifier);
          phoneNumberList.push({
            phone: row.handle_identifier,
            date: safeTimestampToNumber(row.latest_date) ?? 0,
          });
        }
      }
    }

    console.log(
      `Found ${phoneNumberList.length} unique valid phone numbers from unread messages`
    );

    // Step 2: Check which numbers we need to load (not already in cache)
    const numbersToLoad = phoneNumberList
      .filter((item) => !contactCache.has(item.phone))
      .map((item) => item.phone);

    // Step 3: Load contacts only for the specific phone numbers we need
    if (numbersToLoad.length > 0) {
      console.log(
        `Loading contacts for ${numbersToLoad.length} new phone numbers...`
      );
      await loadContactsForNumbers(numbersToLoad);
    }

    // Step 4: For each chat, get the unread messages
    const conversations = chats.map((chat) => {
      // Get unread messages for this chat
      const messagesStmt = db!.prepare(`
        SELECT 
          m.ROWID,
          m.guid,
          m.text,
          m.attributedBody,
          CAST(m.date AS TEXT) as date,
          m.is_from_me,
          m.handle_id,
          m.service,
          m.cache_has_attachments,
          m.item_type,
          m.is_read,
          CAST(m.date_read AS TEXT) as date_read,
          m.associated_message_guid,
          m.associated_message_type,
          m.associated_message_emoji,
          h.id as handle_identifier
        FROM message m
        INNER JOIN chat_message_join cmj ON m.ROWID = cmj.message_id
        LEFT JOIN handle h ON m.handle_id = h.ROWID
        WHERE cmj.chat_id = ?
          AND m.is_read = 0
          AND m.is_from_me = 0
          AND m.item_type = 0
          AND m.is_finished = 1
          AND m.is_system_message = 0
        ORDER BY m.date DESC
      `);

      const messageRows = messagesStmt.all(chat.ROWID) as Array<{
        ROWID: number;
        guid: string;
        text: string | null;
        attributedBody: Buffer | null;
        date: string;
        is_from_me: number;
        handle_id: number | null;
        service: string | null;
        cache_has_attachments: number;
        item_type: number;
        is_read: number;
        date_read: string | null;
        associated_message_guid: string | null;
        associated_message_type: number | null;
        associated_message_emoji: string | null;
        handle_identifier: string | null;
      }>;

      const unreadMessages = messageRows.map((row) => {
        // Extract text (handles both plain text and attributedBody)
        const messageText = extractMessageText(row.text, row.attributedBody);

        return {
          id: String(row.ROWID),
          guid: row.guid,
          text: messageText,
          attributedBody: null,
          date: safeTimestampToNumber(row.date) ?? 0,
          isFromMe: row.is_from_me === 1,
          handleId: row.handle_id ? String(row.handle_id) : null,
          service: row.service,
          cacheHasAttachments: row.cache_has_attachments === 1,
          itemType: row.item_type,
          isRead: row.is_read === 1,
          dateRead: safeTimestampToNumber(row.date_read),
          associatedMessageGuid: row.associated_message_guid,
          associatedMessageType: row.associated_message_type,
          associatedMessageEmoji: row.associated_message_emoji,
          conversationId: String(chat.ROWID),
          chatIdentifier: chat.chat_identifier,
          displayName: chat.display_name,
          handleIdentifier: row.handle_identifier,
          contactName: row.handle_identifier
            ? lookupContactName(row.handle_identifier)
            : null,
        };
      });

      return {
        id: String(chat.ROWID),
        guid: chat.guid,
        chatIdentifier: chat.chat_identifier,
        displayName: chat.display_name,
        style: chat.style,
        serviceName: chat.service_name,
        lastReadMessageTimestamp: safeTimestampToNumber(
          chat.last_read_message_timestamp
        ),
        unreadCount: Number(chat.unread_count),
        lastActivity: safeTimestampToNumber(chat.last_activity) ?? 0,
        unreadMessages,
      };
    });

    const totalUnread = conversations.reduce(
      (sum, conv) => sum + conv.unreadCount,
      0
    );

    return {
      success: true,
      conversations,
      totalUnread,
    };
  } catch (error: any) {
    console.error("Error getting unread conversations:", error);
    return {
      success: false,
      error: error.message,
      conversations: [],
      totalUnread: 0,
    };
  } finally {
    if (db) {
      db.close();
    }
  }
});

// Get recent messages for a specific conversation
ipcMain.handle(
  "get-conversation-messages",
  async (_, chatId: string, limit: number = 5) => {
    let db: DatabaseSync | null = null;
    try {
      db = new DatabaseSync(CHAT_DB_PATH, { readOnly: true });

      // Get recent messages for this chat (regardless of read status)
      const messagesStmt = db.prepare(`
      SELECT 
        m.ROWID,
        m.guid,
        m.text,
        m.attributedBody,
        CAST(m.date AS TEXT) as date,
        m.is_from_me,
        m.handle_id,
        m.service,
        m.cache_has_attachments,
        m.item_type,
        m.is_read,
        CAST(m.date_read AS TEXT) as date_read,
        m.associated_message_guid,
        m.associated_message_type,
        m.associated_message_emoji,
        h.id as handle_identifier
      FROM message m
      INNER JOIN chat_message_join cmj ON m.ROWID = cmj.message_id
      LEFT JOIN handle h ON m.handle_id = h.ROWID
      INNER JOIN chat c ON cmj.chat_id = c.ROWID
      WHERE c.guid = ?
        AND m.item_type = 0
        AND m.is_finished = 1
        AND m.is_system_message = 0
      ORDER BY m.date DESC
      LIMIT ?
    `);

      const messageRows = messagesStmt.all(chatId, limit) as Array<{
        ROWID: number;
        guid: string;
        text: string | null;
        attributedBody: Buffer | null;
        date: string;
        is_from_me: number;
        handle_id: number | null;
        service: string | null;
        cache_has_attachments: number;
        item_type: number;
        is_read: number;
        date_read: string | null;
        associated_message_guid: string | null;
        associated_message_type: number | null;
        associated_message_emoji: string | null;
        handle_identifier: string | null;
      }>;

      // Load contacts for phone numbers in these messages
      const phoneNumbers = messageRows
        .map((m) => m.handle_identifier)
        .filter(
          (h): h is string =>
            h !== null && !h.includes("@") && isValidPhoneNumber(h)
        );

      if (phoneNumbers.length > 0) {
        const numbersToLoad = phoneNumbers.filter(
          (num) => !contactCache.has(num)
        );
        if (numbersToLoad.length > 0) {
          await loadContactsForNumbers(numbersToLoad);
        }
      }

      const messages = messageRows.map((msg) => {
        const contactName = msg.handle_identifier
          ? contactCache.get(msg.handle_identifier) || null
          : null;

        return {
          id: msg.guid,
          text: extractMessageText(msg.text, msg.attributedBody),
          date: safeTimestampToNumber(msg.date) ?? 0,
          isFromMe: msg.is_from_me === 1,
          handleIdentifier: msg.handle_identifier,
          contactName,
          service: msg.service,
          cacheHasAttachments: msg.cache_has_attachments === 1,
          isRead: msg.is_read === 1,
          dateRead: msg.date_read ? safeTimestampToNumber(msg.date_read) : null,
          associatedMessageGuid: msg.associated_message_guid,
          associatedMessageType: msg.associated_message_type,
          associatedMessageEmoji: msg.associated_message_emoji,
        };
      });

      return {
        success: true,
        messages: messages.reverse(), // Reverse to get chronological order
      };
    } catch (error: any) {
      console.error("Error getting conversation messages:", error);
      return {
        success: false,
        error: error.message,
        messages: [],
      };
    } finally {
      if (db) {
        db.close();
      }
    }
  }
);

/**
 * Generate text suggestions using OpenAI
 */
async function generateSuggestionsWithOpenAI(
  lastMessages: Array<{ text: string | null; isFromMe: boolean }>,
  mode: "tab" | "agent",
  draft?: string
): Promise<{ suggestions: string[]; rationales?: string[] }> {
  const apiKey = process.env.OPENAI_API_KEY;

  if (!apiKey) {
    throw new Error("OPENAI_API_KEY environment variable not set");
  }

  // Truncate message context to avoid excessive tokens
  const truncatedMessages = lastMessages
    .filter((m) => m.text)
    .slice(-5)
    .map((m) => ({
      role: m.isFromMe ? "assistant" : "user",
      content: (m.text || "").substring(0, 200), // truncate each message
    }));

  let systemPrompt = "";
  let userPrompt = "";

  if (mode === "tab") {
    systemPrompt = `You are a helpful SMS text message assistant. Generate 3 short, natural text message responses based on the conversation context. The responses should be casual, concise (1-2 sentences max), and contextually appropriate for SMS.`;

    if (draft) {
      userPrompt = `Based on the conversation and the user's draft message "${draft}", suggest 3 ways to complete or improve this message. Keep them short and natural for SMS.`;
    } else {
      userPrompt = `Suggest 3 natural, short responses to continue this conversation.`;
    }
  } else {
    // agent mode
    systemPrompt = `You are an expert SMS conversation assistant. Analyze the conversation and generate 3 distinct response options with different tones/approaches. For each option, also provide a brief 1-sentence rationale explaining the tone or strategy.`;

    if (draft) {
      userPrompt = `The user wants to say: "${draft}". Provide 3 different ways to express this sentiment, each with a different tone or approach. Format your response as JSON: {"options": ["text1", "text2", "text3"], "rationales": ["rationale1", "rationale2", "rationale3"]}`;
    } else {
      userPrompt = `Provide 3 response options with different tones/strategies. Format as JSON: {"options": ["text1", "text2", "text3"], "rationales": ["rationale1", "rationale2", "rationale3"]}`;
    }
  }

  const messages = [
    { role: "system", content: systemPrompt },
    ...truncatedMessages,
    { role: "user", content: userPrompt },
  ];

  try {
    const response = await fetch("https://api.openai.com/v1/chat/completions", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${apiKey}`,
      },
      body: JSON.stringify({
        model: "gpt-4o-mini",
        messages: messages,
        temperature: 0.8,
        max_tokens: 300,
      }),
    });

    if (!response.ok) {
      const errorData = await response.json().catch(() => ({}));
      throw new Error(
        `OpenAI API error: ${response.status} ${response.statusText} - ${JSON.stringify(errorData)}`
      );
    }

    const data = await response.json();
    const content = data.choices[0]?.message?.content;

    if (!content) {
      throw new Error("No content in OpenAI response");
    }

    if (mode === "agent") {
      // Parse JSON response
      try {
        const parsed = JSON.parse(content);
        return {
          suggestions: parsed.options || [],
          rationales: parsed.rationales || [],
        };
      } catch (e) {
        // Fallback: split by newlines
        const lines = content
          .trim()
          .split("\n")
          .filter((l: string) => l.trim());
        return {
          suggestions: lines.slice(0, 3),
          rationales: lines.slice(0, 3).map(() => "Response option"),
        };
      }
    } else {
      // tab mode: split by newlines or numbered list
      const lines = content
        .trim()
        .split("\n")
        .map((l: string) => l.replace(/^\d+[\.)]\s*/, "").trim())
        .filter((l: string) => l.length > 0);

      return {
        suggestions: lines.slice(0, 3),
      };
    }
  } catch (error) {
    console.error("OpenAI API error:", error);
    throw error;
  }
}

// IPC handler for generating suggestions
ipcMain.handle(
  "generate-suggestions",
  async (_event, chatGuid: string, mode: "tab" | "agent", draft?: string) => {
    let db: DatabaseSync | null = null;
    try {
      // Fetch recent messages for context
      db = new DatabaseSync(CHAT_DB_PATH, { readOnly: true });

      const messagesStmt = db.prepare(`
        SELECT 
          m.text,
          m.attributedBody,
          m.is_from_me
        FROM message m
        INNER JOIN chat_message_join cmj ON m.ROWID = cmj.message_id
        INNER JOIN chat c ON cmj.chat_id = c.ROWID
        WHERE c.guid = ?
        ORDER BY m.date DESC
        LIMIT 5
      `);

      const messageRows = messagesStmt.all(chatGuid) as Array<{
        text: string | null;
        attributedBody: Buffer | null;
        is_from_me: number;
      }>;

      const messages = messageRows
        .map((msg) => ({
          text: extractMessageText(msg.text, msg.attributedBody),
          isFromMe: msg.is_from_me === 1,
        }))
        .reverse(); // chronological order

      // Call OpenAI
      const result = await generateSuggestionsWithOpenAI(messages, mode, draft);

      return {
        success: true,
        suggestions: result.suggestions,
        rationales: result.rationales,
      };
    } catch (error: any) {
      console.error("Error generating suggestions:", error);
      return {
        success: false,
        suggestions: [],
        error: error.message || "Failed to generate suggestions",
      };
    } finally {
      if (db) {
        db.close();
      }
    }
  }
);

// Helper function to escape AppleScript strings
function escapeAppleScriptString(str: string): string {
  // Replace backslashes first, then quotes
  return str.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

// AppleScript execution handler
ipcMain.handle(
  "send-imessage",
  async (_event, recipient: string, messageText: string) => {
    try {
      // Escape strings for AppleScript
      const escapedRecipient = escapeAppleScriptString(recipient);
      const escapedMessage = escapeAppleScriptString(messageText);

      // Build AppleScript with proper escaping
      // Use AppleScript's quoted form for safer string handling

      const appleScript = `
set recipient to "${escapedRecipient}"
set messageText to "${escapedMessage}"

set h to ""

-- Try to find contact by name first
try
  tell application "Contacts"
    set p to first person whose name is recipient
    if (count of phones of p) > 0 then
      set h to value of first phone of p
    else if (count of emails of p) > 0 then
      set h to value of first email of p
    end if
  end tell
on error
  -- If not found as contact name, assume recipient is already phone/email
  set h to recipient
end try

if h is "" then
  error "Recipient has no phone or email in Contacts."
end if

-- Open the Messages thread via URL scheme
do shell script "open " & quoted form of ("imessage://" & h)

-- Type and send message automatically
delay 1
tell application "System Events"
  tell process "Messages"
    keystroke messageText
    delay 0.2
    key code 36 -- press Return (sends the message)
  end tell
end tell
`.trim();

      // Execute using osascript via stdin using echo and pipe
      // This avoids heredoc quoting issues
      const command = `echo ${JSON.stringify(appleScript)} | osascript`;

      const { stderr } = await execAsync(command);

      if (
        stderr &&
        !stderr.includes("Messages") &&
        !stderr.includes("execution error")
      ) {
        throw new Error(stderr);
      }

      return {
        success: true,
        message: "Message sent successfully!",
      };
    } catch (error) {
      console.error("AppleScript error:", error);
      return {
        success: false,
        error:
          error instanceof Error ? error.message : "Unknown error occurred",
      };
    }
  }
);
