import "dotenv/config";
import * as os from "os";
import { pathToFileURL } from "url";
import { config } from "dotenv";
import {
  app,
  BrowserWindow,
  ipcMain,
  shell,
  systemPreferences,
  screen,
} from "electron";
import path from "path";
import fs from "fs";
import { spawn, exec } from "child_process";
import { promisify } from "util";
import { randomUUID } from "crypto";
import { runAgentStream } from "../agent/run";
import type { AgentContext } from "../agent";
import { generateObject } from "ai";
import { openai } from "@ai-sdk/openai";
import { z } from "zod";
import {
  statsResponseSchema,
  unreadMessagesResponseSchema,
  conversationsResponseSchema,
  chatMessagesResponseSchema,
  StatsResponse,
  UnreadMessagesResponse,
  ConversationsResponse,
  ChatMessagesResponse,
  MessageDTO,
  ConversationDTO,
} from "./types/imessage";

// Load .env file - dotenv/config loads from process.cwd() by default
// Also try loading from apps/overlay/.env explicitly (doesn't error if file doesn't exist)
const overlayEnvPath = path.join(__dirname, "../../.env");
config({ path: overlayEnvPath });

const execAsync = promisify(exec);

const CLI_BASENAME =
  process.platform === "win32" ? "imessage_query.exe" : "imessage_query";
const CLI_ENV_OVERRIDE = process.env.IMESSAGE_QUERY_PATH;
const CLI_DEV_BINARY = path.resolve(
  app.getAppPath(),
  "../../ml/imessage_query/target/release",
  CLI_BASENAME
);
const CLI_PROJECT_DIR = path.resolve(
  app.getAppPath(),
  "../../ml/imessage_query"
);
const SKIP_CLI_BUILD = process.env.IMESSAGE_QUERY_SKIP_BUILD === "1";

let cachedCliPath: string | null = null;
let cliBuildPromise: Promise<void> | null = null;

function resolveCliBinaryPath(): string {
  if (cachedCliPath) {
    return cachedCliPath;
  }

  if (CLI_ENV_OVERRIDE && CLI_ENV_OVERRIDE.length > 0) {
    cachedCliPath = CLI_ENV_OVERRIDE;
    return cachedCliPath;
  }

  if (app.isPackaged) {
    cachedCliPath = path.join(process.resourcesPath, CLI_BASENAME);
  } else {
    cachedCliPath = CLI_DEV_BINARY;
  }

  return cachedCliPath;
}

function ensureCliExists(cliPath: string): boolean {
  return fs.existsSync(cliPath);
}

async function buildCliBinary(): Promise<void> {
  console.log("[cli] Building imessage_query (cargo build --release)...");

  await new Promise<void>((resolve, reject) => {
    const child = spawn("cargo", ["build", "--release"], {
      cwd: CLI_PROJECT_DIR,
      stdio: "inherit",
    });

    child.on("error", (error) => {
      reject(error);
    });

    child.on("close", (code) => {
      if (code === 0) {
        resolve();
      } else {
        reject(new Error(`cargo build exited with code ${code ?? "unknown"}`));
      }
    });
  });
}

async function ensureCliReady(): Promise<string> {
  const cliPath = resolveCliBinaryPath();

  if (ensureCliExists(cliPath)) {
    return cliPath;
  }

  if (app.isPackaged) {
    throw new Error(
      `imessage_query binary missing at ${cliPath}. Please reinstall the application.`
    );
  }

  if (SKIP_CLI_BUILD) {
    throw new Error(
      `imessage_query binary not found at ${cliPath} and automatic build disabled (IMESSAGE_QUERY_SKIP_BUILD=1).`
    );
  }

  if (!cliBuildPromise) {
    cliBuildPromise = buildCliBinary().finally(() => {
      cliBuildPromise = null;
    });
  }

  await cliBuildPromise;

  if (!ensureCliExists(cliPath)) {
    throw new Error(
      `imessage_query binary still missing at ${cliPath} after build attempt.`
    );
  }

  return cliPath;
}

async function runImessageCli<T>(
  args: string[],
  schema: z.ZodType<T>
): Promise<T> {
  const cliPath = await ensureCliReady();

  return await new Promise<T>((resolve, reject) => {
    const child = spawn(cliPath, args, {
      stdio: ["ignore", "pipe", "pipe"],
    });

    let stdout = "";
    let stderr = "";

    child.stdout.on("data", (chunk) => {
      stdout += chunk.toString();
    });

    child.stderr.on("data", (chunk) => {
      stderr += chunk.toString();
    });

    child.on("error", (error) => {
      reject(error);
    });

    child.on("close", (code) => {
      if (code !== 0) {
        const message = stderr.trim() || `exit code ${code}`;
        reject(new Error(`imessage_query failed: ${message}`));
        return;
      }

      try {
        const parsed = schema.parse(JSON.parse(stdout));
        resolve(parsed);
      } catch (error: any) {
        reject(
          new Error(
            `Failed to parse imessage_query output: ${error.message}
stdout: ${stdout}
stderr: ${stderr}`
          )
        );
      }
    });
  });
}

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Vite
// plugin that tells the Electron app where to look for the Vite-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_VITE_DEV_SERVER_URL: string;
declare const MAIN_WINDOW_VITE_NAME: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require("electron-squirrel-startup")) {
  app.quit();
}

const CHAT_DB_PATH = path.join(os.homedir(), "Library/Messages/chat.db");

// Contact cache to avoid re-lookups
const contactCache = new Map<string, string>(); // phone number -> contact name
let contactMap: Map<string, string> | null = null;
let contactMapLoading = false;

// Store the original bottom position to keep it fixed during resizes
let originalBottomY: number | null = null;

const createWindow = (): void => {
  // Get screen dimensions
  const { width: screenWidth, height: screenHeight } =
    screen.getPrimaryDisplay().workAreaSize;

  const windowWidth = 500;
  const windowHeight = 50;
  const bottomMargin = 2; // Distance from bottom of screen

  // Calculate position: centered horizontally, at bottom vertically
  const x = Math.floor((screenWidth - windowWidth) / 2);
  const y = screenHeight - windowHeight - bottomMargin;

  // Create the browser window.
  const mainWindow = new BrowserWindow({
    width: windowWidth,
    height: windowHeight,
    x: x,
    y: y,
    frame: false,
    transparent: true, // Remove backdrop shadow
    hasShadow: true, // Enable window shadow on macOS
    backgroundColor: "#00000000", // Fully transparent background
    webPreferences: {
      preload: path.join(__dirname, "preload.js"),
      nodeIntegration: false,
      contextIsolation: true,
    },
  });

  // and load the index.html of the app.
  if (MAIN_WINDOW_VITE_DEV_SERVER_URL) {
    mainWindow.loadURL(MAIN_WINDOW_VITE_DEV_SERVER_URL);
  } else {
    mainWindow.loadFile(
      path.join(__dirname, `../renderer/${MAIN_WINDOW_VITE_NAME}/index.html`)
    );
  }

  // Store the original bottom position once window is ready
  mainWindow.once("ready-to-show", () => {
    const cb = mainWindow.getContentBounds();
    originalBottomY = cb.y + cb.height;
  });

  // Open the DevTools.
  // Commented out to prevent auto-opening DevTools in development
  // if (!app.isPackaged) {
  //   mainWindow.webContents.openDevTools();
  // }
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on("ready", () => {
  createWindow();
  ensureCliReady().catch((error) => {
    console.error("[cli] Failed to prepare imessage_query:", error);
  });
});

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on("window-all-closed", () => {
  if (process.platform !== "darwin") {
    app.quit();
  }
});

ipcMain.handle(
  "read-file-as-data-url",
  async (_event, filePath: string, mimeType?: string | null) => {
    try {
      if (!filePath || typeof filePath !== "string") return null;
      const expanded = filePath.startsWith("~")
        ? path.join(os.homedir(), filePath.slice(1))
        : filePath;
      const data = await fs.promises.readFile(expanded);
      const mime = mimeType || "application/octet-stream";
      const base64 = data.toString("base64");
      return `data:${mime};base64,${base64}`;
    } catch (e) {
      console.error("[Attachments] read-file-as-data-url failed:", e);
      return null;
    }
  }
);

app.on("activate", () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.

/**
 * Close window handler
 */
ipcMain.on("close-window", () => {
  const window = BrowserWindow.getFocusedWindow();
  if (window) {
    window.close();
  }
});

/**
 * Resize window handler — expand upward while keeping bottom fixed
 */
ipcMain.on("resize-window", (event, newHeight: number, newWidth?: number) => {
  const win = BrowserWindow.fromWebContents(event.sender);
  if (!win) return;

  // Work in content-space so transparent/frame/shadow don't skew math
  const cb = win.getContentBounds();

  // Device-pixel alignment to avoid 1px jitter on scaled displays
  const scale =
    screen.getDisplayMatching(cb).scaleFactor ||
    screen.getPrimaryDisplay().scaleFactor ||
    1;
  const align = (v: number) => Math.round(v * scale) / scale;

  // Use the stored original bottom position, or calculate it if not set
  if (originalBottomY === null) {
    originalBottomY = cb.y + cb.height;
  }

  // Always anchor to the original bottom position
  const targetY = align(originalBottomY - newHeight);

  // Use provided width or keep current width
  const targetWidth = newWidth ? align(newWidth) : align(cb.width);

  // Center horizontally if width changes
  const { width: screenWidth } = screen.getPrimaryDisplay().workAreaSize;
  const targetX = newWidth
    ? align((screenWidth - targetWidth) / 2)
    : align(cb.x);

  win.setContentBounds(
    {
      x: targetX,
      y: targetY,
      width: targetWidth,
      height: align(newHeight),
    },
    /* animate */ true
  );
});

/**
 * Check if we have Full Disk Access to read the iMessage database
 */
ipcMain.handle("check-database-access", async () => {
  try {
    // Check if file exists and is readable
    if (!fs.existsSync(CHAT_DB_PATH)) {
      return {
        hasAccess: false,
        path: CHAT_DB_PATH,
        error: "Database file not found",
      };
    }

    // Try to get file stats to verify read access
    const stats = fs.statSync(CHAT_DB_PATH);

    return {
      hasAccess: true,
      path: CHAT_DB_PATH,
      fileSize: stats.size,
      lastModified: stats.mtime,
    };
  } catch (error: any) {
    return {
      hasAccess: false,
      path: CHAT_DB_PATH,
      error: error.message,
    };
  }
});

/**
 * Get database statistics (file size, last modified, etc.)
 */
ipcMain.handle("get-database-stats", async () => {
  try {
    const response = await runImessageCli(["stats"], statsResponseSchema);

    return {
      success: true,
      ...response,
      path: CHAT_DB_PATH,
    };
  } catch (error: any) {
    console.error("Error getting database stats via CLI:", error);
    return {
      success: false,
      error: error?.message ?? String(error),
    };
  }
});

/**
 * Get list of tables in the database
});

/**
 * Get list of tables in the database
 */
ipcMain.handle("get-database-tables", async () => {
  try {
    // Use stats command as a lightweight health check to ensure CLI can read the DB.
    await runImessageCli(["stats"], statsResponseSchema);

    return {
      success: true,
      tables: [],
      totalCount: 0,
      note: "Table listing is not available in CLI mode",
    };
  } catch (error: any) {
    console.error("Error verifying database access via CLI:", error);
    return {
      success: false,
      error: error?.message ?? String(error),
      tables: [],
      totalCount: 0,
    };
  }
});

/**
 * Open System Preferences to Full Disk Access pane
});

/**
 * Open System Preferences to Full Disk Access pane
 */
ipcMain.handle("open-system-preferences", async () => {
  try {
    // Open the Full Disk Access settings pane
    shell.openExternal(
      "x-apple.systempreferences:com.apple.preference.security?Privacy_AllFiles"
    );
    return { success: true };
  } catch (error: any) {
    return {
      success: false,
      error: error.message,
    };
  }
});

/**
 * Helper function to safely convert Apple timestamp (which can be very large) to number
 * Apple timestamps are in nanoseconds since 2001-01-01
 */
function safeTimestampToNumber(timestamp: any): number | null {
  if (timestamp === null || timestamp === undefined) {
    return null;
  }

  // If it's already a number and within safe range, return it
  if (typeof timestamp === "number") {
    return timestamp;
  }

  // If it's a string (from CAST AS TEXT), parse it
  if (typeof timestamp === "string") {
    try {
      // Use BigInt to handle large numbers, then convert to regular number
      const bigIntValue = BigInt(timestamp);
      // Convert to number (may lose precision but that's okay for timestamps)
      return Number(bigIntValue);
    } catch {
      return null;
    }
  }

  // Try parsing as BigInt if it's some other type
  try {
    const bigIntValue = BigInt(timestamp);
    return Number(bigIntValue);
  } catch {
    // Fallback to direct conversion
    return Number(timestamp);
  }
}

/**
 * Check if a text chunk looks like binary metadata/artifacts
 */
function isBinaryArtifact(chunk: string): boolean {
  const lower = chunk.toLowerCase();

  // Filter out NSObject-related patterns
  if (
    lower.includes("nsattributedstring") ||
    lower.includes("nsobject") ||
    lower.includes("nsdictionary") ||
    lower.includes("nsmutable") ||
    lower.includes("nsstring") ||
    lower.includes("nsnumber") ||
    lower.includes("nsvalue") ||
    lower.includes("streamtyped") ||
    lower.includes("__kim")
  ) {
    return true;
  }

  // Filter out binary plist markers (X$version, Y$archiver, T$top, etc.)
  if (/\$version|\$archiver|\$top|\$objects|X\$|Y\$|T\$|Z\$/.test(chunk)) {
    return true;
  }

  // Filter out NS.rangeval, NS.special, NS.location patterns
  if (/NS\.(rangeval|special|location|objects|classname)/i.test(chunk)) {
    return true;
  }

  // Filter out patterns that look like binary metadata (containing $ and version/archiver)
  if (
    chunk.includes("$") &&
    (lower.includes("version") ||
      lower.includes("archiver") ||
      lower.includes("objects"))
  ) {
    return true;
  }

  // Filter out pure numbers
  if (/^\d+$/.test(chunk)) {
    return true;
  }

  return false;
}

/**
 * Remove binary artifact patterns from text, even when embedded in longer strings
 */
function removeBinaryArtifacts(text: string): string {
  let cleaned = text;

  // Remove concatenated patterns like "X$versionY$archiverT$topX$objects" (no spaces between)
  // This catches patterns where multiple $ markers are concatenated together
  cleaned = cleaned.replace(
    /[XYZ]\$[a-zA-Z]+[XYZ]\$[a-zA-Z]+[TZ]\$[a-zA-Z]+[XYZ]\$[a-zA-Z]+/g,
    ""
  );

  // Remove individual binary plist patterns (X$version, Y$archiver, T$top, Z$objects, etc.)
  cleaned = cleaned.replace(/[XYZ]\$[a-zA-Z]+/g, "");
  cleaned = cleaned.replace(/T\$[a-zA-Z]+/g, "");
  cleaned = cleaned.replace(/\$[a-zA-Z]+/g, "");

  // Remove NS. patterns (NS.rangeval, NS.special, NS.location, etc.)
  // Also handle cases like "NS.rangeval.locationZNS.special" where Z might be between
  cleaned = cleaned.replace(/NS\.[a-zA-Z]+/g, "");
  cleaned = cleaned.replace(/[A-Z]NS\.[a-zA-Z]+/g, ""); // Handle ZNS.special, etc.

  // Remove patterns with $ followed by version/archiver/objects/top (with or without surrounding chars)
  cleaned = cleaned.replace(/\S*\$version\S*/gi, "");
  cleaned = cleaned.replace(/\S*\$archiver\S*/gi, "");
  cleaned = cleaned.replace(/\S*\$objects\S*/gi, "");
  cleaned = cleaned.replace(/\S*\$top\S*/gi, "");

  // Remove NSObject class names (with word boundaries)
  cleaned = cleaned.replace(
    /\bNS(AttributedString|Object|Dictionary|Mutable|String|Number|Value|Array|Data)\b/gi,
    ""
  );

  // Remove streamtyped
  cleaned = cleaned.replace(/\bstreamtyped\b/gi, "");

  // Remove __kIM patterns
  cleaned = cleaned.replace(/\b__kIM\w+\b/gi, "");

  // Remove patterns like "rangeval.location" or standalone metadata words
  cleaned = cleaned.replace(
    /\b(rangeval|special|location|objects|classname|archiver|version)\.[a-zA-Z]+\b/gi,
    ""
  );

  // Remove patterns like "locationZNS" where a metadata word is concatenated with NS
  cleaned = cleaned.replace(
    /\b(rangeval|special|location|objects|classname)[A-Z]+NS\b/gi,
    ""
  );

  // Remove standalone metadata words that might appear (rangeval, special, etc.)
  cleaned = cleaned.replace(
    /\b(rangeval|special|location|objects|classname)\b/gi,
    ""
  );

  // Remove any word that contains both a metadata term and NS (like "locationZNS")
  cleaned = cleaned.replace(
    /\b\w*(rangeval|special|location|objects|classname)\w*NS\w*\b/gi,
    ""
  );
  cleaned = cleaned.replace(
    /\b\w*NS\w*(rangeval|special|location|objects|classname)\w*\b/gi,
    ""
  );

  // Clean up multiple spaces and periods/spaces
  cleaned = cleaned.replace(/\s+/g, " ");
  cleaned = cleaned.replace(/\.\s*\./g, "."); // Remove double periods
  cleaned = cleaned.trim();

  return cleaned;
}

/**
 * Helper function to extract text from a message
 * Handles both plain text field and attributedBody binary data
 * Based on research from imessage-db-exploration.md and SQL exploration
 *
 * The attributedBody format stores text as readable UTF-8 strings embedded in the binary data.
 */
function extractMessageText(
  text: string | null,
  attributedBody: Buffer | null
): string | null {
  // If plain text is available, use it
  if (text) {
    return text;
  }

  // Otherwise, try to extract from attributedBody
  if (!attributedBody) {
    return null;
  }

  try {
    const textChunks: string[] = [];

    // Convert to Buffer if it's not already (node-sqlite returns Uint8Array)
    const buffer = Buffer.isBuffer(attributedBody)
      ? attributedBody
      : Buffer.from(attributedBody);

    // Scan the entire buffer sequentially for readable ASCII text sequences
    // Look for sequences of printable ASCII characters (32-126)
    let textStart = -1;
    let textLength = 0;

    for (let i = 0; i < buffer.length; i++) {
      const byte = buffer[i];
      // Only printable ASCII for now (32-126)
      const isPrintable = byte >= 32 && byte <= 126;

      if (isPrintable) {
        if (textStart === -1) {
          textStart = i;
        }
        textLength++;
      } else {
        // End of printable sequence - extract if long enough (at least 3 chars)
        if (textLength >= 3 && textStart !== -1) {
          try {
            const chunk = buffer.subarray(textStart, textStart + textLength);
            const decoded = chunk.toString("ascii");
            // Must contain letters and be meaningful
            if (decoded.length >= 3 && /[A-Za-z]/.test(decoded)) {
              const trimmed = decoded.trim();
              // Filter out binary artifacts
              if (!isBinaryArtifact(trimmed)) {
                textChunks.push(trimmed);
              }
            }
          } catch (e) {
            // Skip invalid sequences
          }
        }
        textStart = -1;
        textLength = 0;
      }
    }

    // Handle text that extends to end of buffer
    if (textLength >= 3 && textStart !== -1) {
      try {
        const chunk = buffer.subarray(textStart, textStart + textLength);
        const decoded = chunk.toString("ascii");
        if (decoded.length >= 3 && /[A-Za-z]/.test(decoded)) {
          const trimmed = decoded.trim();
          if (!isBinaryArtifact(trimmed)) {
            textChunks.push(trimmed);
          }
        }
      } catch (e) {
        // Skip invalid sequences
      }
    }

    if (textChunks.length === 0) {
      return null;
    }

    // Join chunks, removing duplicates and cleaning up
    // Sort by length (longest first) to prioritize actual message content
    const sortedChunks = [...new Set(textChunks)].sort(
      (a, b) => b.length - a.length
    );

    // Take the longest chunks (likely the actual message)
    const topChunks = sortedChunks
      .slice(0, 3)
      .filter((c) => c.length >= 3 && !isBinaryArtifact(c));
    let result = topChunks.join(" ");

    // If we didn't get good results, try all chunks (but still filter artifacts)
    if (result.length < 5) {
      result = sortedChunks.filter((c) => !isBinaryArtifact(c)).join(" ");
    }

    // Final cleanup - remove any remaining binary artifacts that might have slipped through
    // First, remove artifact patterns from the entire string
    result = removeBinaryArtifacts(result);

    // Then split by spaces and filter out individual words that are artifacts
    const words = result.split(/\s+/).filter((word) => {
      // Keep words that don't look like binary artifacts
      return !isBinaryArtifact(word) && word.length > 0;
    });

    result = words
      .join(" ")
      .replace(/\s+/g, " ") // Multiple spaces to single
      .replace(/\n{3,}/g, "\n\n") // Max 2 consecutive newlines
      .trim();

    // Must have meaningful content
    if (result.length < 2 || !/[A-Za-z]/.test(result)) {
      return null;
    }

    return result;
  } catch (error) {
    console.error("Error extracting text from attributedBody:", error);
    return null;
  }
}

/**
 * Normalize phone number for matching (remove formatting, keep + and digits)
 */
function normalizePhoneNumber(phone: string): string {
  // Remove all non-digit characters except +
  return phone.replace(/[^\d+]/g, "");
}

/**
 * Find all AddressBook databases (same as orchestrate.py find_addressbook_dbs)
 */
function findAddressBookDbs(): string[] {
  const pattern = path.join(
    os.homedir(),
    "Library/Application Support/AddressBook/Sources/*/AddressBook-v22.abcddb"
  );

  // Use glob pattern matching
  const matches: string[] = [];
  try {
    const sourcesDir = path.join(
      os.homedir(),
      "Library/Application Support/AddressBook/Sources"
    );
    if (fs.existsSync(sourcesDir)) {
      const sources = fs.readdirSync(sourcesDir);
      for (const source of sources) {
        const dbPath = path.join(sourcesDir, source, "AddressBook-v22.abcddb");
        if (fs.existsSync(dbPath)) {
          matches.push(dbPath);
        }
      }
    }
  } catch (error) {
    console.error("Error finding AddressBook databases:", error);
  }

  return matches;
}

/**
 * Load all contacts from AddressBook database directly (same as orchestrate.py)
 * Uses SQLite to query ZABCDPHONENUMBER and ZABCDRECORD tables
 */
async function loadContactMap(): Promise<Map<string, string>> {
  // Return existing map if already loaded
  if (contactMap) {
    return contactMap;
  }

  // If already loading, wait a bit and return empty map
  if (contactMapLoading) {
    return new Map();
  }

  contactMapLoading = true;

  try {
    const addressbookPaths = findAddressBookDbs();

    if (addressbookPaths.length === 0) {
      contactMap = new Map();
      contactMapLoading = false;
      return contactMap;
    }

    const map = new Map<string, string>();

    // Use Node's built-in sqlite module (requires Node 22.5.0+)
    const { DatabaseSync } = require("node:sqlite");

    for (const dbPath of addressbookPaths) {
      try {
        // Query the AddressBook database (same as orchestrate.py get_contact_name)
        const db = new DatabaseSync(dbPath, { open: true, readOnly: true });

        const rows = db
          .prepare(
            `
          SELECT c.ZFIRSTNAME, c.ZLASTNAME, p.ZFULLNUMBER
          FROM ZABCDPHONENUMBER p
          JOIN ZABCDRECORD c ON p.ZOWNER = c.Z_PK
        `
          )
          .all();

        db.close();

        // Process each contact-phone pair (same as orchestrate.py)
        for (const row of rows) {
          const firstName = row.ZFIRSTNAME || "";
          const lastName = row.ZLASTNAME || "";
          const fullName = `${firstName} ${lastName}`.trim();
          const phoneRaw = row.ZFULLNUMBER;

          if (!fullName || !phoneRaw) continue;

          const normalized = normalizePhoneNumber(phoneRaw);

          // Store many different format variations to maximize matching (same as orchestrate.py)
          const variants = new Set<string>();

          // Add the normalized version
          variants.add(normalized);

          // Add without leading +
          if (normalized.startsWith("+")) {
            variants.add(normalized.slice(1));
          }

          // Add without +1 prefix
          if (normalized.startsWith("+1")) {
            variants.add(normalized.slice(2));
          }

          // Add without 1 prefix
          if (normalized.startsWith("1") && normalized.length === 11) {
            variants.add(normalized.slice(1));
          }

          // Add last 10 digits (US phone number)
          if (normalized.length >= 10) {
            variants.add(normalized.slice(-10));
          }

          // Add last 7 digits (local number)
          if (normalized.length >= 7) {
            variants.add(normalized.slice(-7));
          }

          // Add with +1 prefix if not present and looks like US number
          if (!normalized.startsWith("+") && normalized.length === 10) {
            variants.add("+1" + normalized);
            variants.add("1" + normalized);
          }

          // Store all variants
          for (const variant of variants) {
            if (variant.length >= 7) {
              // Only store variants with reasonable length
              map.set(variant, fullName);
            }
          }
        }
      } catch (error) {
        console.error(`Error querying AddressBook database:`, error);
      }
    }

    contactMap = map;
    contactMapLoading = false;
    return map;
  } catch (error: any) {
    console.error("Error loading contacts:", error);
    // Return empty map on error
    contactMap = new Map();
    contactMapLoading = false;
    return contactMap;
  }
}

/**
 * Load contacts for specific phone numbers
 * Loads the full contact map once, then uses it for lookups
 */
async function loadContactsForNumbers(phoneNumbers: string[]): Promise<void> {
  // If map is already loaded, we don't need to do anything
  if (contactMap) {
    return;
  }

  // Load the full contact map
  const map = await loadContactMap();

  // Cache the lookups
  for (const phone of phoneNumbers) {
    const name = lookupContactName(phone);
    if (name) {
      contactCache.set(phone, name);
    }
  }
}

/**
 * Check if a phone number is valid (not a short code or invalid)
 */
function isValidPhoneNumber(phone: string): boolean {
  const normalized = normalizePhoneNumber(phone);
  // Must be at least 10 digits (US phone number) or have + and be reasonable length
  if (normalized.startsWith("+")) {
    // International: +1XXXXXXXXXX (11 chars minimum) or longer
    return normalized.length >= 11;
  }
  // Domestic: at least 10 digits
  return normalized.length >= 10;
}

/**
 * Look up contact name from phone number or email
 * Uses pre-loaded contact map (must be loaded separately)
 */
function lookupContactName(identifier: string): string | null {
  if (!identifier) return null;

  // Check cache first
  if (contactCache.has(identifier)) {
    return contactCache.get(identifier) || null;
  }

  // Email addresses - return as is for now
  if (identifier.includes("@")) {
    return null;
  }

  // Phone number - check contact map
  if (!contactMap) {
    return null;
  }

  // Try various normalized formats (matching what we store in the map)
  const normalized = normalizePhoneNumber(identifier);
  const formats = new Set<string>();

  // Add original and normalized
  formats.add(identifier);
  formats.add(normalized);

  // Add without leading +
  if (normalized.startsWith("+")) {
    formats.add(normalized.slice(1));
  }

  // Add without +1 prefix
  if (normalized.startsWith("+1")) {
    formats.add(normalized.slice(2));
  }

  // Add without 1 prefix
  if (normalized.startsWith("1") && normalized.length === 11) {
    formats.add(normalized.slice(1));
  }

  // Add last 10 digits (US phone number)
  if (normalized.length >= 10) {
    formats.add(normalized.slice(-10));
  }

  // Add last 7 digits (local number)
  if (normalized.length >= 7) {
    formats.add(normalized.slice(-7));
  }

  // Add with +1 prefix if not present and looks like US number
  if (!normalized.startsWith("+") && normalized.length === 10) {
    formats.add("+1" + normalized);
    formats.add("1" + normalized);
  }

  // Try each format
  for (const format of formats) {
    const name = contactMap.get(format);
    if (name) {
      // Cache it
      contactCache.set(identifier, name);
      return name;
    }
  }

  return null;
}

const conversationMetadataCache = new Map<string, ConversationDTO>();
const conversationIdCache = new Map<number, ConversationDTO>();
const CONVERSATION_LIMITS = ["50", "250", "1000", "2500"] as const;
let conversationCacheHydratedIndex = -1;

async function fetchConversationMetadata(
  chatGuid: string
): Promise<ConversationDTO | null> {
  if (conversationMetadataCache.has(chatGuid)) {
    return conversationMetadataCache.get(chatGuid)!;
  }

  const limits = ["50", "250", "1000", "2500"];
  for (const limit of limits) {
    try {
      const response = await runImessageCli(
        ["conversations", "--limit", limit],
        conversationsResponseSchema
      );

      for (const convo of response.data) {
        conversationMetadataCache.set(convo.guid, convo);
      }

      if (conversationMetadataCache.has(chatGuid)) {
        return conversationMetadataCache.get(chatGuid)!;
      }
    } catch (error) {
      console.warn(
        `Failed to fetch conversation metadata (limit=${limit}):`,
        error
      );
      break;
    }
  }

  return conversationMetadataCache.get(chatGuid) ?? null;
}

async function lookupConversationDisplayName(
  chatGuid: string
): Promise<string | undefined> {
  const metadata = await fetchConversationMetadata(chatGuid);
  if (!metadata) {
    return undefined;
  }

  if (metadata.display_name && metadata.display_name.trim().length > 0) {
    return metadata.display_name;
  }

  const participants = metadata.participants ?? [];
  const phoneNumbers = participants.filter(
    (identifier) => !identifier.includes("@") && isValidPhoneNumber(identifier)
  );

  const numbersToLoad = phoneNumbers.filter((num) => !contactCache.has(num));
  if (numbersToLoad.length > 0) {
    await loadContactsForNumbers(numbersToLoad);
  }

  for (const identifier of participants) {
    const name = lookupContactName(identifier);
    if (name) {
      return name;
    }
  }

  if (metadata.chat_identifier) {
    return metadata.chat_identifier;
  }

  return participants[0];
}

function dtoToUnreadMessage(
  dto: any,
  convoMeta?: { chat_identifier?: string | null; display_name?: string | null }
): any {
  return {
    id: String(dto.id),
    guid: dto.guid,
    text: dto.text ?? null,
    attributedBody: null,
    date: dto.date?.raw_ns ?? 0,
    isFromMe: !!dto.is_from_me,
    handleId: dto.handle_id != null ? String(dto.handle_id) : null,
    service: dto.service ?? null,
    cacheHasAttachments: !!dto.has_attachments,
    itemType: dto.item_type ?? 0,
    isRead: !!dto.is_read,
    dateRead: dto.date_read?.raw_ns ?? null,
    associatedMessageGuid: dto.associated_message_guid ?? null,
    associatedMessageType: dto.associated_message_type ?? null,
    associatedMessageEmoji: dto.associated_message_emoji ?? null,
    conversationId: dto.chat_id != null ? String(dto.chat_id) : "",
    chatIdentifier: convoMeta?.chat_identifier ?? "",
    displayName: convoMeta?.display_name ?? null,
    handleIdentifier: dto.handle_identifier ?? null,
    contactName: dto.handle_identifier
      ? lookupContactName(dto.handle_identifier)
      : null,
  };
}

function dtoToConversationMessage(dto: any): any {
  return {
    id: String(dto.id),
    text: dto.text ?? null,
    date: dto.date?.raw_ns ?? 0,
    isFromMe: !!dto.is_from_me,
    handleIdentifier: dto.handle_identifier ?? null,
    contactName: dto.handle_identifier
      ? lookupContactName(dto.handle_identifier)
      : null,
    service: dto.service ?? null,
    cacheHasAttachments: !!dto.has_attachments,
    attachments: Array.isArray(dto.attachments)
      ? dto.attachments.map((a: any) => ({
          id: Number(a.id),
          guid: a.guid,
          mime_type: a.mime_type ?? null,
          uti: a.uti ?? null,
          filename: a.filename ?? null,
          total_bytes: a.total_bytes ?? null,
          is_sticker: !!a.is_sticker,
        }))
      : [],
    isRead: !!dto.is_read,
    dateRead: dto.date_read?.raw_ns ?? null,
    associatedMessageGuid: dto.associated_message_guid ?? null,
    associatedMessageType: dto.associated_message_type ?? null,
    associatedMessageEmoji: dto.associated_message_emoji ?? null,
  };
}
async function buildAgentContext(
  chatGuid: string,
  messages?: Array<{
    text: string;
    isFromMe: boolean;
    handleId?: string;
    date: number;
  }>
): Promise<AgentContext> {
  const contactName = await lookupConversationDisplayName(chatGuid);

  if (messages && messages.length > 0) {
    return {
      contactName,
      conversation: messages.map((msg) => ({
        isFromMe: msg.isFromMe,
        text: msg.text,
      })),
    };
  }

  try {
    const response = await runImessageCli(
      ["messages", "--chat-guid", chatGuid, "--limit", "30", "--ascending"],
      chatMessagesResponseSchema
    );

    const conversation = response.data.map((msg) => ({
      isFromMe: msg.is_from_me,
      text: msg.text ?? "",
    }));

    return {
      contactName,
      conversation,
    };
  } catch (error) {
    console.error("Error building agent context via CLI:", error);
    return {
      contactName,
      conversation: [],
    };
  }
}

/**
 * Get all unread messages
/**
 * Get all unread messages
 * Returns flat list of unread messages ordered by date (newest first)
 */
ipcMain.handle("get-unread-messages", async (_, limit?: number) => {
  try {
    const args = ["unread"];
    if (typeof limit === "number" && Number.isFinite(limit)) {
      args.push("--limit", String(limit));
    }

    const response = await runImessageCli(args, unreadMessagesResponseSchema);

    // Load contacts for all phone numbers in the messages
    const phoneNumbers = response.data
      .map((m: any) => m.handle_identifier)
      .filter(
        (id: string | null) => id && !id.includes("@") && isValidPhoneNumber(id)
      );
    if (phoneNumbers.length > 0) {
      await loadContactsForNumbers([...new Set(phoneNumbers)]);
    }

    const data = response.data;
    const convMetaById: Record<
      string,
      { chat_identifier?: string | null; display_name?: string | null }
    > = {};
    for (const v of conversationMetadataCache.values()) {
      const anyv: any = v as any;
      if (anyv && anyv.id != null) {
        convMetaById[String(anyv.id)] = {
          chat_identifier: anyv.chat_identifier ?? null,
          display_name: anyv.display_name ?? null,
        };
      }
    }
    const messages = data.map((dto: any) =>
      dtoToUnreadMessage(dto, convMetaById[String(dto.chat_id ?? "")])
    );
    return { success: true, messages, count: messages.length };
  } catch (error: any) {
    console.error("Error getting unread messages via CLI:", error);
    return {
      success: false,
      error: error?.message ?? String(error),
      data: [],
    };
  }
});

/**
 * Get unread messages grouped by conversation/chat
});

/**
 * Get unread messages grouped by conversation/chat
 * Returns conversations with their unread messages
 */
ipcMain.handle("get-unread-conversations", async () => {
  try {
    const args = ["conversations", "--limit", "50"];
    const response = await runImessageCli(args, conversationsResponseSchema);

    const convs = response.data;

    // Fetch unread messages separately
    const unread = await runImessageCli(
      ["unread", "--limit", "2000"],
      unreadMessagesResponseSchema
    );

    // Load contacts for all phone numbers in the unread messages
    const allIdentifiers = unread.data.map((m: any) => m.handle_identifier);
    const phoneNumbers = allIdentifiers.filter(
      (id: string | null) => id && !id.includes("@") && isValidPhoneNumber(id)
    );
    if (phoneNumbers.length > 0) {
      await loadContactsForNumbers([...new Set(phoneNumbers)]);
    }

    // Group unread messages by chat_id
    const byChat: Record<string, any[]> = {};
    for (const m of unread.data) {
      const key = String(m.chat_id ?? "");
      if (!byChat[key]) byChat[key] = [];
      byChat[key].push(
        dtoToUnreadMessage(m, { chat_identifier: null, display_name: null })
      );
    }

    // Map conversations to the expected format
    const conversations = convs
      .filter((c: any) => c.unread_count > 0) // Only include conversations with unread messages
      .map((c: any) => {
        // Try to get a display name: use the one from DB, or look up contact by chat_identifier
        let displayName = c.display_name;
        if (
          !displayName &&
          c.chat_identifier &&
          !c.chat_identifier.includes("@")
        ) {
          const contactName = lookupContactName(c.chat_identifier);
          if (contactName) {
            displayName = contactName;
          }
        }

        // Build a better preview for last message when text is empty (e.g., images)
        let lastMessageText: string | null = c.last_message?.text ?? null;
        if (!lastMessageText && c.last_message?.attachments?.length) {
          const a = c.last_message.attachments[0];
          const mime = String(a?.mime_type || a?.uti || "").toLowerCase();
          if (a?.is_sticker) lastMessageText = "[Sticker]";
          else if (mime.startsWith("image/")) lastMessageText = "[Image]";
          else if (mime.startsWith("video/")) lastMessageText = "[Video]";
          else if (mime.startsWith("audio/")) lastMessageText = "[Audio]";
          else if (mime.includes("pdf")) lastMessageText = "[PDF]";
          else if (mime) lastMessageText = "[Attachment]";
        }

        return {
          id: String(c.id),
          guid: c.guid,
          chatIdentifier: c.chat_identifier ?? "",
          displayName: displayName ?? null,
          style: null as any,
          serviceName: c.service ?? null,
          lastReadMessageTimestamp: null as any,
          unreadCount: c.unread_count ?? 0,
          lastActivity: c.last_activity?.raw_ns ?? 0,
          unreadMessages: byChat[String(c.id)] ?? [],
          lastMessageText,
        };
      });

    const totalUnread = conversations.reduce(
      (s: number, c: any) => s + (c.unreadCount || 0),
      0
    );

    return { success: true, conversations, totalUnread };
  } catch (error: any) {
    console.error("Error getting unread conversations via CLI:", error);
    return {
      success: false,
      error: error?.message ?? String(error),
      conversations: [],
      totalUnread: 0,
    };
  }
});

ipcMain.handle(
  "get-conversation-messages",
  async (_, chatGuid: string, limit: number = 5) => {
    if (!chatGuid) {
      return {
        success: false,
        error: "Conversation GUID is required",
      };
    }

    try {
      // Fetch messages in descending order (latest first) to get the most recent ones
      const args = [
        "messages",
        "--chat-guid",
        chatGuid,
        "--limit",
        String(limit ?? 5),
      ];

      const response = await runImessageCli(args, chatMessagesResponseSchema);

      // Load contacts for all phone numbers in the messages
      const phoneNumbers = response.data
        .map((m: any) => m.handle_identifier)
        .filter(
          (id: string | null) =>
            id && !id.includes("@") && isValidPhoneNumber(id)
        );
      if (phoneNumbers.length > 0) {
        await loadContactsForNumbers([...new Set(phoneNumbers)]);
      }

      // Reverse to get ascending order (oldest first) for display
      const data = response.data
        .reverse()
        .map((dto: any) => dtoToConversationMessage(dto));
      const withAttachments = data.filter(
        (m: any) => Array.isArray(m.attachments) && m.attachments.length > 0
      ).length;
      if (withAttachments > 0) {
        console.log(
          `[Attachments] get-conversation-messages: ${withAttachments} messages include attachments`
        );
      }
      return { success: true, messages: data };
    } catch (error: any) {
      console.error("Error getting conversation messages via CLI:", error);
      return {
        success: false,
        error: error?.message ?? String(error),
        data: [],
      };
    }
  }
);

ipcMain.handle("resolve-file-url", async (_event, filePath: string) => {
  try {
    if (!filePath || typeof filePath !== "string") return null;
    const expanded = filePath.startsWith("~")
      ? path.join(os.homedir(), filePath.slice(1))
      : filePath;
    return pathToFileURL(expanded).toString();
  } catch (e) {
    return null;
  }
});

ipcMain.handle(
  "run-agent",
  async (
    event,
    query: string,
    chatGuid: string,
    messages: Array<{
      text: string;
      isFromMe: boolean;
      handleId?: string;
      date: number;
    }>
  ) => {
    if (!query || !query.trim()) {
      return {
        success: false,
        error: "Query is required to run the agent",
      };
    }
    if (!chatGuid) {
      return {
        success: false,
        error: "Conversation GUID is required",
      };
    }

    try {
      const context = await buildAgentContext(chatGuid, messages);
      const agentResult = await runAgentStream(query, context);
      const streamId = randomUUID();
      const webContents = event.sender;
      const DEBUG = process.env.TEXTREME_AGENT_DEBUG === "1";

      if (DEBUG) {
        console.log(
          `[agent] run-agent invoked (streamId=${streamId}) for conversation=${chatGuid}`
        );
      }

      const channel = `agent-stream:${streamId}`;

      setImmediate(async () => {
        try {
          for await (const agentEvent of agentResult.fullStream) {
            if (webContents.isDestroyed()) {
              break;
            }
            webContents.send(channel, agentEvent);
          }

          const finalOutput = await agentResult.getFinalOutput();
          if (!webContents.isDestroyed()) {
            if (DEBUG) {
              console.log(
                `[agent] Stream complete (streamId=${streamId}), delivering final output`
              );
            }
            webContents.send(channel, {
              type: "complete",
              finalOutput,
            });
          }
        } catch (streamError: any) {
          if (DEBUG) {
            console.error(
              `[agent] Stream error (streamId=${streamId}):`,
              streamError
            );
          }
          if (!webContents.isDestroyed()) {
            webContents.send(channel, {
              type: "error",
              error:
                streamError instanceof Error
                  ? streamError.message
                  : String(streamError),
            });
          }
        }
      });

      return {
        success: true,
        streamId,
      };
    } catch (error: any) {
      console.error("Error running agent:", error);
      return {
        success: false,
        error: error instanceof Error ? error.message : "Failed to run agent",
      };
    }
  }
);

/**
 * Generate text completions using custom Modal endpoint
 */
async function generateCompletionsWithModal(
  lastMessages: Array<{ text: string | null; isFromMe: boolean; contactName: string | null; date: number }>,
  draft: string,
  displayName: string | null,
  chatIdentifier: string
): Promise<string[]> {
  // Ensure contact map is loaded before lookup (same as orchestrate.py does)
  await loadContactMap();

  // Resolve contact name using the same method as orchestrate.py
  // Priority: displayName from DB -> lookupContactName(chatIdentifier) -> chatIdentifier itself
  let contactName = displayName;
  if (!contactName) {
    contactName = lookupContactName(chatIdentifier);
  }
  if (!contactName) {
    // Fallback to chatIdentifier itself (phone number or email)
    contactName = chatIdentifier;
  }
  
  // Filter messages by 12-hour gap (same as extract_training_pairs.py line 509-512)
  const CONVERSATION_GAP_HOURS = 12;
  const filteredMessages: typeof lastMessages = [];
  
  if (lastMessages.length > 0) {
    const mostRecentDate = lastMessages[lastMessages.length - 1].date;
    
    // Walk backward from most recent, stop when we hit a 12-hour gap
    for (let i = lastMessages.length - 1; i >= 0; i--) {
      const msg = lastMessages[i];
      const timeGapSeconds = (mostRecentDate - msg.date) / 1_000_000_000;
      const timeGapHours = timeGapSeconds / 3600;
      
      if (timeGapHours > CONVERSATION_GAP_HOURS) {
        break; // stop including older messages
      }
      
      filteredMessages.unshift(msg);
    }
  }
  
  if (filteredMessages.length < lastMessages.length) {
    console.log(`Filtered ${lastMessages.length - filteredMessages.length} messages older than ${CONVERSATION_GAP_HOURS}h (kept ${filteredMessages.length})`);
  }
  
  // Format messages in training format: "{sender}: {content}"
  const formattedMessages = filteredMessages
    .map((msg) => {
      const sender = msg.isFromMe ? "ME" : contactName;
      const text = msg.text || "";
      // Escape newlines for JSONL format (same as extract_training_pairs.py line 549)
      const escapedText = text.replace(/\n/g, '\\n');
      return `${sender}: ${escapedText}`;
    });

  const input = formattedMessages.join('\n');
  
  // Prepare partial response if draft exists
  const partialResponse = draft ? `ME: ${draft}` : undefined;

  // Modal endpoint configuration
  const MODAL_ENDPOINT = "https://connorff--textreme-no-tags-inference-web-dev.modal.run";
  // Use different temperatures for varied suggestions
  const TEMPERATURES = [0.2, 0.5, 0.9];

  console.log("Request parameters:", {
    sender: "ME",
    input: input,
    partial_response: partialResponse,
    temperatures: TEMPERATURES,
  });

  try {
    // Make three parallel requests with different temperatures
    const requests = TEMPERATURES.map(async (temperature) => {
      const params = new URLSearchParams({
        temperature: temperature.toString(),
        sender: "ME",
        input: input,
        partial_response: partialResponse,
      });

      const url = `${MODAL_ENDPOINT}?${params.toString()}`;

      const response = await fetch(url, {
        method: "GET",
        headers: {
          Accept: "text/plain",
        },
      });

      if (!response.ok) {
        throw new Error(
          `Modal API returned ${response.status}: ${response.statusText}`
        );
      }

      const text = await response.text();
      
      console.log(`Response (T=${temperature}):`, text);
      
      // For partial completions, the model returns the continuation as the first line
      // (with "ME: " prefix), followed by optional additional messages (with "ME: " prefix)
      // We only want the first line which completes the partial draft
      const lines = text.split('\n');
      const firstLine = lines[0].replace(/%$/, '').trim();
      
      // Extract content after "ME: " prefix
      const match = firstLine.match(/^ME:\s*(.+)$/);
      const completion = match ? match[1].trim() : firstLine;
      
      console.log(`Parsed completion (T=${temperature}):`, completion);
      return completion;
    });

    const completions = await Promise.all(requests);
    
    // Deduplicate and filter similar completions
    const uniqueCompletions = deduplicateCompletions(completions);
    
    return uniqueCompletions;
  } catch (error) {
    console.error("Modal API error:", error);
    throw error;
  }
}

/**
 * Deduplicate completions and filter out very similar ones
 * Returns up to 3 diverse completions
 */
function deduplicateCompletions(completions: string[]): string[] {
  if (completions.length === 0) return completions;
  
  const unique: string[] = [];
  
  for (const completion of completions) {
    const normalized = completion.toLowerCase().trim();
    
    // Check if this completion is too similar to any we've already added
    const isSimilar = unique.some(existing => {
      const existingNormalized = existing.toLowerCase().trim();
      
      // Exact match
      if (normalized === existingNormalized) return true;
      
      // Calculate similarity using simple word overlap
      const words1 = new Set(normalized.split(/\s+/));
      const words2 = new Set(existingNormalized.split(/\s+/));
      
      const intersection = new Set([...words1].filter(w => words2.has(w)));
      const union = new Set([...words1, ...words2]);
      
      // Jaccard similarity > 0.8 means very similar
      const similarity = intersection.size / union.size;
      return similarity > 0.8;
    });
    
    if (!isSimilar) {
      unique.push(completion);
    }
  }
  
  // If we filtered too many, return the original completions
  // (better to show duplicates than nothing)
  return unique.length > 0 ? unique : completions;
}

// IPC handler for generating autocomplete suggestions with messages from UI
ipcMain.handle(
  "generate-completions",
  async (
    _event,
    messages: Array<{ text: string | null; isFromMe: boolean; contactName: string | null; date: number }>,
    draft: string,
    displayName: string | null,
    chatIdentifier: string
  ) => {
    try {
      const completions = await generateCompletionsWithModal(
        messages,
        draft,
        displayName,
        chatIdentifier
      );

      return {
        success: true,
        suggestions: completions,
      };
    } catch (error: any) {
      console.error("Error generating completions:", error);
      return {
        success: false,
        suggestions: [],
        error: error.message || "Failed to generate completions",
      };
    }
  }
);

// Helper function to escape AppleScript strings
function escapeAppleScriptString(str: string): string {
  // Replace backslashes first, then quotes
  return str.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

// Helper function to execute AppleScript using shell command with timeout
async function executeAppleScript(
  script: string,
  timeoutMs: number = 10000
): Promise<void> {
  // Escape the script for shell: replace single quotes with '\'' and wrap in single quotes
  // This ensures the script is safely passed to the shell
  const escapedScript = script.replace(/'/g, "'\\''");
  // Use printf to pipe the script to osascript, which handles newlines and special chars better
  const command = `printf '%s\n' '${escapedScript}' | osascript`;

  // Create a promise that times out
  const timeoutPromise = new Promise<never>((_, reject) => {
    setTimeout(
      () =>
        reject(
          new Error(`AppleScript execution timed out after ${timeoutMs}ms`)
        ),
      timeoutMs
    );
  });

  try {
    const { stdout, stderr } = await Promise.race([
      execAsync(command),
      timeoutPromise,
    ]);

    // Some AppleScript errors are expected (like Messages app warnings)
    // Only throw if it's a real error
    if (
      stderr &&
      !stderr.includes("Messages") &&
      !stderr.includes("execution error")
    ) {
      throw new Error(stderr);
    }
  } catch (error) {
    console.error("AppleScript execution error:", error);
    throw error;
  }
}

// Helper function to mark conversation as read by clicking on it in Messages
async function markConversationAsReadViaClick(
  recipient: string
): Promise<void> {
  try {
    const escapedRecipient = escapeAppleScriptString(recipient);

    const appleScript = `
set recipient to "${escapedRecipient}"

set h to ""

-- Try to find contact by name first
try
  tell application "Contacts"
    set p to first person whose name is recipient
    if (count of phones of p) > 0 then
      set h to value of first phone of p
    else if (count of emails of p) > 0 then
      set h to value of first email of p
    end if
  end tell
on error
  -- If not found as contact name, assume recipient is already phone/email
  set h to recipient
end try

if h is "" then
  set h to recipient
end if

-- Activate Messages and click on the conversation to mark it as read
tell application "Messages"
  activate
  delay 0.5
end tell

tell application "System Events"
  tell process "Messages"
    -- Wait for Messages window to be ready
    repeat until exists window 1
      delay 0.1
    end repeat
    
    -- Try to find and click the conversation in the sidebar
    try
      -- Look for the conversation row that contains the recipient identifier
      set conversationRows to rows of table 1 of scroll area 1 of splitter group 1 of window 1
      repeat with aRow in conversationRows
        try
          set rowText to value of static text 1 of aRow
          if rowText contains h or rowText contains recipient then
            -- Click on the row to open the conversation and mark as read
            click aRow
            delay 0.2
            exit repeat
          end if
        end try
      end repeat
    on error errMsg
      -- If UI structure is different, try alternative approach
      log "Could not find conversation row: " & errMsg
    end try
  end tell
end tell

-- Hide Messages app again
tell application "System Events"
  set visible of process "Messages" to false
end tell

delay 0.3
`.trim();

    await executeAppleScript(appleScript);
  } catch (error: any) {
    console.error("Error marking conversation as read via click:", error);
    // Don't throw - this is a best-effort operation
  }
}

// AppleScript execution handler
ipcMain.handle(
  "send-imessage",
  async (_event, recipient: string, messageText: string) => {
    try {
      if (!recipient || recipient.trim() === "") {
        return {
          success: false,
          error: "Recipient is empty",
        };
      }

      if (!messageText || messageText.trim() === "") {
        return {
          success: false,
          error: "Message text is empty",
        };
      }

      // Escape strings for AppleScript
      const escapedRecipient = escapeAppleScriptString(recipient);
      const escapedMessage = escapeAppleScriptString(messageText);

      // Build AppleScript with proper escaping
      // Use AppleScript's quoted form for safer string handling

      const appleScript = `
set recipient to "${escapedRecipient}"
set messageText to "${escapedMessage}"

set h to ""

-- Try to find contact by name first
try
  tell application "Contacts"
    set p to first person whose name is recipient
    if (count of phones of p) > 0 then
      set h to value of first phone of p
    else if (count of emails of p) > 0 then
      set h to value of first email of p
    end if
  end tell
on error
  -- If not found as contact name, assume recipient is already phone/email
  set h to recipient
end try

if h is "" then
  error "Recipient has no phone or email in Contacts."
end if

-- Ensure Messages is running and responsive
tell application "Messages"
  -- Briefly activate to ensure it's responsive
  activate
  delay 0.1
end tell

-- Hide Messages immediately
tell application "System Events"
  set visible of process "Messages" to false
end tell

-- Send message
tell application "Messages"
  set targetService to 1st service whose service type = iMessage
  set targetBuddy to buddy h of targetService
  send messageText to targetBuddy
end tell

-- Small delay to ensure message is sent
delay 0.2
`.trim();

      // Execute using spawn with stdin for reliable script execution
      await executeAppleScript(appleScript, 5000); // 5 second timeout

      // After successfully sending, mark the conversation as read (non-blocking)
      markConversationAsReadViaClick(recipient).catch(() => {
        // Silently fail - this is non-critical
      });

      return {
        success: true,
        message: "Message sent successfully!",
      };
    } catch (error) {
      console.error("Error sending iMessage:", error);
      return {
        success: false,
        error:
          error instanceof Error ? error.message : "Unknown error occurred",
      };
    }
  }
);
